### ISSUE TITLE
*cider-error* buffer seem to have buffer-undo activated

### ISSUE THREAD

**Issue by Arcanum-XIII** [clojure-emacs/cider#1004]
I have this error quite often :

Warning (undo): Buffer *cider-error*' undo info was 14111968 bytes long. The undo info was discarded because it exceededundo-outer-limit'.

(Origin of the error seem to be an issue between piggieback/weasel | boot-cljs-repl | cider, filling the cider-error buffer)

I don't think this buffer need the undo to be activated ?

**Comment by cichli** [comment]
I don't think there should ever be that much data in the error buffer. Can you share the versions of cider/cider-nrepl/clojurescript/piggieback/weasel, or (even better) a project that will let me replicate?

**Comment by Arcanum-XIII** [comment]
latest cider from melpa | cider nrepl 9.0-snapshot | piggieback should be 0.16-snapshot and weasel-6.0 (if my understanding of the boot-cljs-repl is correct - meaning I override piggieback/weasel in my local build.boot)
Boot is updated daily with 'boot -u'

I agree that something fishy is going on - especially since most of the time the *cider-error* buffer is "looking" empty - the joy of clojurescript ?

**Comment by noprompt** [comment]
I'm seeing the same warning as well with `[piggieback "0.1.6-SNAPSHOT"]`, `[weasel "0.6.0"]`, and cider 0.8.2. It seems to happen at random intervals. Sometimes my session will lock up in minutes; other times hours. This is the warning I get

```
Warning (undo): Buffer `*cider-error*' undo info was 15964992 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.
```

**Comment by noprompt** [comment]
I think this happens because it is getting hung up on dumping the exception info which contains the entire ClojureScript compiler analyzer data (this can be enormous).

**Comment by cichli** [comment]
@noprompt you're right - [`cljs.repl/evaluate-form`](https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/repl.clj#L379), which piggieback [relies upon](https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L116), used to print a stacktrace and return nil when an exception was thrown. It now throws an `ExceptionInfo` whose `data` map includes (amongst other things) the entire CLJS REPL environment (and by extension the analyzer/compiler environment). The middleware pprints this to a string [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/stacktrace.clj#L120), which pegs a Java process at 100% until I kill it (I didn't stick around for it to start killing emacs).

A workaround for now is to set `cider-stacktrace-print-level` to a low number like 5. Adding an equivalent option for setting `*print-length*` helps a bit but at a depth of 13 you hit what appears to be all of the non-minified Closure library in a single string.

@bbatsov a prudent solution for now is probably to blacklist the `:repl-env` key. Maybe in the long term we should use the inspector for optional browsing of this data rather than always printing it.

**Comment by bbatsov** [comment]
> @bbatsov a prudent solution for now is probably to blacklist the :repl-env key. Maybe in the long term we should use the inspector for optional browsing of this data rather than always printing it.

Fine by me.
