### ISSUE TITLE
Debugger improvement: don't print result of a step to string

### ISSUE THREAD

**Issue by DesmondHayes** [clojure-emacs/cider#1049]
Consider an example:
```clojure
(defn foo [x y]
  (symbol (str x "/" y)))
```
I want to debug the following call to 'foo:
```clojure
(foo "bar" "baz")
```
Debugger step results as I press "n":

| N | Now (bad)     | Should be (good) |
|---|---------------|------------------|
| 1 | "\"bar\""     | "bar"            |
| 2 | "\"baz\""     | "baz"            |
| 3 | "\"bar/baz\"" | "bar/baz"        |
| 4 | "bar/baz"     | bar/baz          |

**Comment by Malabarba** [comment]
Thanks for the report. I'll look into this.

**Comment by cichli** [comment]
@Malabarba nREPL already does the equivalent of `pr-str` on `:value` slots in responses (see [this middleware](https://github.com/clojure/tools.nrepl/blob/master/src/main/clojure/clojure/tools/nrepl/middleware/pr_values.clj)), so I think we're double-printing. This likely only happens with more recent versions of nREPL (>= 0.27) due to the way middlewares are ordered changing. We have a few options:

* Include a non-nil value in the `:printed-value` slot of the response, so `pr-values` will skip printing
* Keep doing the printing ourselves in the debugger middleware but use a different slot name than `:value`
* Remove the call to `pr-str` from the debugger middleware, and add `#'pr-values` to the `:requires` set of `wrap-debug`, to guarantee that the slot will be printed (like [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/inspect.clj#L83))

`:printed-value` was only added to nREPL 0.2.10, and `pr-values` is _technically_ an nREPL implementation detail, so maybe option 2 is the simplest. Thoughts?

**Comment by Malabarba** [comment]
I added the manual printing because it seemed to be necessary on the
nrepl version I had. Otherwise I ran into issues. I think my version
was `0.2.6`, so it's consistent with what you're saying, @cichli.

And yes, I think option 2 is the simplest.
