### ISSUE TITLE
^M is printed in the repl on windows

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1100]
```
user> (+ 1 1)
2^M
```

This seems to be a minor regression after rewriting the pprint functionality?  Any thoughts on this, @cichli?

**Comment by cichli** [comment]
Related: #474, #532

Looking at the old pprinting code, we didn't have anything special to handle this, and AFAIK `pprint` will always use platform-specific newlines (see [here](https://github.com/clojure/clojure/blob/201a0dd9701e1a0ee3998431241388eb4a854ebf/src/clj/clojure/pprint/pretty_writer.clj#L99)), but `cider-repl.el` always inserts UNIX-style newlines - so emacs can't figure out what `buffer-file-coding-system` should be set to.

Hmmm... what do you see in `*nrepl-messages*` if you eval the following two forms in the REPL (with `cider-repl-use-pretty-printing` enabled? Does the `out` slot for the latter have UNIX newlines and the `pprint-out` slot for the former have Windows newlines?
```clojure
(+ 1 1)

(clojure.pprint/pprint (+ 1 1))
```

I think the easiest fix is to just strip `\r` from everything we print at the REPL, rather than worry about coding systems and platform-specific newlines.

**Comment by expez** [comment]
```
(<-
  id  "1872"
  pprint-out  "2^M\n"
  session  "6dd7f9fb-c00e-4087-bcf4-d3ab7a5db105"
)

(<-
  id  "1873"
  out  "2^M\n"
  session  "6dd7f9fb-c00e-4087-bcf4-d3ab7a5db105"
)
(<-
  id  "1873"
  pprint-out  "nil^M\n"
  session  "6dd7f9fb-c00e-4087-bcf4-d3ab7a5db105"
)
```

`^M` everywhere!  Just stripping `\r` sounds like the easiest solution to me too.

**Comment by bbatsov** [comment]
> I think the easiest fix is to just strip \r from everything we print at the REPL, rather than worry about coding systems and platform-specific newlines.

Sounds fine by me.

**Comment by expez** [comment]
ping @cichli, you assigned this to yourself.  Did you start on this? :)

**Comment by expez** [comment]
:+1:

**Comment by cichli** [comment]
@expez just pushed the fix to master :).

The carriage return removal I've added happens at the bencode decoding level, rather than when printing to the REPL - since the same issue could presumably arise anywhere else we're using printed output (any of the eval-and-print commands, and also in the error buffer when we show pretty-printed stacktrace data). This also avoids people having to deal with the same problem downstream (see clojure-emacs/ac-cider@fe3491bfb404a082c2a9ac5a08fcac300e8d3651).

Escaped newlines are of course unaffected:

```clojure
user> (pr-str "a\r\nb")
"a\r\nb"
```
