### ISSUE TITLE
Why has C-u C-M-x behavior changed?

### ISSUE THREAD

**Issue by malcolmsparks** [clojure-emacs/cider#1102]
d6b6d7758383f395852f73e674a7659d7103263b brought in a change that has changed the behavior of C-u C-M-x, which is a key-binding I use all the time in my coding.

Prior to this commit it would paste the result of the eval into the current buffer. Now it invokes some debugger - I've looked through the code to see where the original functionality is available, but  can't find it, so I can't rebind my key-binding to the old behavior. 

Is there any discussion anywhere about why this was changed? I'm keen to stay up-to-date with CIDER to help report issues, but this is the second time in recent memory that a very old established keybinding has been suddenly changed, which must be damaging CIDER's reputation.

**Comment by expez** [comment]
`cider-eval-last-sexp-and-replace` looks to be the closest to what `C-u C-M-X` previously did.  I think a good policy going forward is to leave the old function unchanged, when a keybinding is updated, so users can opt to rebind it.

The keybinding `C-u C-M-x` was chosen because this was already an established keybinding for instrumenting a form (most notably in edebug).

In general it's becoming **really** hard to find keybindings for new functionality added to cider, so from time to time less frequently used functions will have to give way for new ones.

**Comment by bbatsov** [comment]
@malcolmsparks I understand your frustrations, but we had very good reason to do this change - as @expez mentioned this keybinding has been in Emacs Lisp since forever, so it's familiar to many Emacs users.

**Comment by malcolmsparks** [comment]
I understand the need to progress things towards more general consistency, it's just a pain with these things because of muscle memory (which can be retrained). @Malabarba pointed out to me that C-u C-x C-e kind of does the same thing, so at least I have an alternative - thanks for everyone being so kind and understanding.
