### ISSUE TITLE
End of buffer error after test failure

### ISSUE THREAD

**Issue by AshtonKem** [clojure-emacs/cider#1143]
Steps to reproduce
1. Find a testing namespace
2. Eval NS
3. Run all tests (success)
4. Run individual test (success)
5. Edit a test to fail.
6. Run all tests (failure correctly reported)
7. Run failing test individually (End of buffer error)
8. Run all tests (End of buffer error).

After repeating this process, the only way to return to successful tests is to restart Cider.

**Comment by bbatsov** [comment]
I'm guessing this happens on 0.9.0, right?

**Comment by bbatsov** [comment]
I can't reproduce this with a simple project created with `lein new` and the follow tests in it:

```
(deftest a-test
  (testing "something"
    (is (= 1 1))))

(deftest b-test
  (testing "something else"
    (is (= 1 1))))
```

**Comment by AshtonKem** [comment]
Correct. 

--
Ashton

**Comment by bbatsov** [comment]
Can you cook some minimal project in which the problem can be reproduced?

**Comment by weejulius** [comment]
steps to reproduce:

load from file and run tests, it works correctly.
and then load the test form again and run tests, you will see the error.

**Comment by bbatsov** [comment]
@weejulius Yep, that did it. The problem is that when you're doing interactive evaluation the location metadata for the form is not set and this causes this error. There's nothing I can do about the location metadata and I'd advise everyone affected by this to ask @cemerick to merge the patch attached to http://dev.clojure.org/jira/browse/NREPL-59

I can, however, figure out some way to show a nicer message. 

Here's some background info about the problem https://github.com/clojure-emacs/cider/issues/1088 and why this was changed in CIDER 0.9.
