### ISSUE TITLE
[FR] Clojure repl mode history search

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1166]
I'd be awesome if `(kbd "C-c C-r")` searched backwards over saved REPL input history. Mashing `(kbd "C-up")` gets old fast especially when replaying history.

**Comment by bbatsov** [comment]
This is related to https://github.com/clojure-emacs/cider/issues/709. I've generally ignored REPL issues because I felt the comint switch was right around the corner. I'm not sure if @vspinu is making progress there, though. Guess I might end up doing this myself if I find time for it.

**Comment by vspinu** [comment]
> I felt the comint switch was right around the corner. I'm not sure if @vspinu is making progress there, though

It was around the corner back in December :) Then I changed jobs and started freelancing. My world is upside down since then. I have virtually no time for open source anymore contrary to what I would have expected. 

Anyways, comint rebase is still very high on my agenda, as it is nrepl refactoring, but it is unlikely to happen in the weeks to come. So please feel free to give it a stab if you have time.

**Comment by bbatsov** [comment]
@arrdem volunteered to work on #709, so I'll close this.
