### ISSUE TITLE
README lacks Company setup steps

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1173]
![screenshot 2015-06-29 11 57 09](https://cloud.githubusercontent.com/assets/704767/8415789/23abc6fa-1e56-11e5-95a4-976ab60609a7.png)

Autocomplete is a pretty critical feature, especially to newbies. Should probably fix this :P

**Comment by Malabarba** [comment]
Are there any setup steps? I thought it worked out of the box.
Or maybe it needs a `(company-mode 1)`?

**Comment by Malabarba** [comment]
Are there any setup steps? I thought it worked out of the box.
Or maybe it needs a `(company-mode 1)`?

**Comment by bbatsov** [comment]
Guess there was also some confusing about the name of the package.

**Comment by cobalamin** [comment]
@bbatsov Mainly this, actually. I kept looking for `company-mode` because it is mentioned as such everywhere. After that it was rather easy peasy.

But maybe other setup instruction help, like pointing out that you need to bind a key to `company-complete` to trigger it manually (as is standard workflow in many IDEs), would be good for beginners who just want to get up and running.

**Comment by arrdem** [comment]
+1 to "add a key binding"

**Comment by bbatsov** [comment]
> But maybe other setup instruction help, like pointing out that you need to bind a key to company-complete to trigger it manually (as is standard workflow in many IDEs), would be good for beginners who just want to get up and running.

@expez Maybe you can add something about this as well - basically bind `company-begin` to something and maybe mention how to disable the auto-display of candidates.
