### ISSUE TITLE
Debugging tests

### ISSUE THREAD

**Issue by grammati** [clojure-emacs/cider#1251]
It would be nice if "C-u C-M-x" would instrument deftest forms for debugging, as it does for defn.

**Comment by Malabarba** [comment]
Which version are you on? I think the debugger in the snapshot releases already does that.

**Comment by bbatsov** [comment]
@Malabarba so, should I just close this?

**Comment by grammati** [comment]
Turning on *print-meta*, deftest forms certainly appear to be instrumented. But I cannot find a way to actually debug them. Executing the instrumented test (eg: with C-c M-, or calling it in the repl) runs it normally, without stopping in the debugger.

I have been working around this when I need to by pulling the body of the test out into a separate function, which can be debugged. eg:

    (defn a-test-impl []
      (foo blah))
    (deftest a-test
      (a-test-impl))

Then if I instrument the "-impl" function and run the test, I can debug.

I am on 0.10-0-SNAPSHOT (cider-nrepl-0.10.0-20150809.163707-19.jar).

And thanks for all your work on the debugger! It's awesome!

**Comment by Malabarba** [comment]
Ok, thanks for checking. I'll look into it over the weekend.

**Comment by jeffvalk** [comment]
Quick note from having implemented `cider-test`:

The `clojure.test` machinery reads the actual test function from the `:test` metadata on a var. (It was designed this way so that you could define a function and its test together -- the latter as metadata on the former.)

As a result, the `deftest` macro doesn't create a var bound to a test function as one might guess. Rather it creates a var with the test function associated as `:test` metadata. The var itself is bound to a function that invokes the test metadata function. See [here](https://github.com/clojure/clojure/blob/1d5237f9d7db0bc5f6e929330108d016ac7bf76c/src/clj/clojure/test.clj#L608).

Essentially, `deftest` function bodies are not defined in any namespace -- they exist only as metadata. For the purposes of the debugger, this might require a special case.

HTH!

@Malabarba Great work on the debugger!

**Comment by Malabarba** [comment]
Well, that explains it then. The debugger macroexpands the code before instrumenting it for good. And the test metadata is being created at macroexpansion, before the debugger has a chance to instrument it. 

@jeffvalk  Thanks for the info. :) I'll have to think about how we can solve this. 
The sanest option I can think of is for us to (during the instrumentation step) also look inside the the `:test` metadata and instrument whatever code happens to be in there too. Hopefully that won't break anything. :P

**Comment by jeffvalk** [comment]
@Malabarba You might just consider walking all `IMeta` objects' metadata generically during instrumentation. Then `:test` wouldn't be a special case. I'd be surprised if there weren't a number of other projects (albeit a small one) that attach functions as metadata.

**Comment by Malabarba** [comment]
Yes, that's possible too. I'm a little afraid of running into conflicts. Most libs that set metadata don't expect it to be changed behind their back.
But if we restrict ourselves to only instrument when the metadata is a function then the risk is probably very small.

**Comment by jeffvalk** [comment]
Sounds solid to me!

**Comment by Malabarba** [comment]
@bbatsov @expez Could someone tag this as help-wanted or something like that?
It is a relatively simple fix, but I'm swamped for the next week or so.

**Comment by grammati** [comment]
Here is my first attempt, but it's not working, and I'm not sure why. @Malabarba, if you have a few minutes, could you take a quick look and tell me if my approach is obviously wrong? Thanks.

https://github.com/grammati/cider-nrepl/commit/37f2c35a41c3651516e8977b71bded2b4e636c1f
