### ISSUE TITLE
cider-refresh's optional arg isn't optional

### ISSUE THREAD

**Issue by root42** [clojure-emacs/cider#1369]
I am using the following snippet to run `cider-refresh` automatically whenever I save a buffer running `cider-mode`:

```
  (add-hook 'cider-mode-hook 
  	    '(lambda () (add-hook 'after-save-hook 
  				  '(lambda () 
  				     (if (and (boundp 'cider-mode) cider-mode)
  					 (cider-refresh)
  				       )))))
```

My `project.clj` looks like this:

```
(defproject foo "0.1.0-SNAPSHOT"
  :description "foo."
  :url "http://foo"
  :license {:name "Simplified BSD License"
            :url "http://www.linfo.org/bsdlicense.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :main core.foo
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :plugins
  [
   [org.clojure/tools.namespace "0.2.11"]
   [cider/cider-nrepl "0.10.0-SNAPSHOT"]
   ]
  )
```

Whenever I run `cider-refresh` interactively, it works. I can also bind it to some key. But when I hit `C-x C-s`, I get this error:

```
run-hooks: Wrong type argument: number-or-marker-p, nil
```

I figure this is a bug? Or am I using the function wrong?

**Comment by expez** [comment]
This is a bug in the sense that the `&optional arg` isn't really optional, but it's also not meant to be used this way.

You can fix the problem by calling the function with `1` instead of nothing.  

Also, I'm not entirely sure, but I think you might be appending a new version of your after-save-hook each time you open a cider-mode buffer.  What's buffer-local and global can sometimes be confusing so I might be wrong.

**Comment by root42** [comment]
Well, `C-h f` says about `add-hook`:

```
(add-hook HOOK FUNCTION &optional APPEND LOCAL)

Add to the value of HOOK the function FUNCTION.
FUNCTION is not added if already present.
```

My hope was that the `lambda` will be recognized as already present. But this might of course be delusional! :) So I better put it in a named function.

**Comment by root42** [comment]
So, I tested by changing the code from above to run `(cider-refresh 1)` and this works. May I ask what the non-optional argument is for? And what would be the correct way to refresh upon save? I think it might be overkill to do a whole `cider-refresh`...? I would assume that only the current buffer would need to be refreshed in the REPL...?

**Comment by Malabarba** [comment]
I pushed a fix so that the optional argument is really optional now. As for your code:

1. `add-hook` checks for equality with `equal`, which means that it *will* indeed identify that your lambda is already present and will *not* add it twice.
2. You should not quote your lambdas.
3. In your second `add-hook`, you have to use the fourth arg to add the hook locally. Otherwise you will add this function to the `after-save-hook` for *all* files.

**Comment by Malabarba** [comment]
In summary, here's another way you could write your code (though it's
usually recommended to not use anonymous functions in hooks):

    (add-hook 'cider-mode-hook 
              (lambda () (add-hook 'after-save-hook
                              (lambda () 
                                (when (cider-connected-p)
                                  (cider-refresh)))
                              nil
                              'local)))

**Comment by bbatsov** [comment]
While, this is not really related to the problem, I believe it's not a good idea to invoke `cider-refresh` on save. That's a huge overkill.

**Comment by root42** [comment]
@bbatsov Ok, very insightful comments here. But what would one do instead, so that the REPL is always in sync with the emacs buffers?
