### ISSUE TITLE
Debugger skips local variables if they have the same name as a function from core

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1428]
While working on my slides for tomorrow's CIDER talk I noticed that when I instrument this:

```
defn fibo-iter
  ([n] (fibo-iter 0 1 n))
  ([curr next n]
   (cond
     (zero? n) curr
     :else (recur next (+ curr next) (dec n))))
```

stepping passes over the first argument of `recur` (`next`).

**Comment by Malabarba** [comment]
Actually, I don't think it's about the recur.

That's probably because your variable has the name of a core function. 
The debugger avoids displaying the value of stuff from core otherwise it would be much noisier. 

It's still a bug (the debugger has enough information to know that that's a local var), but you should be able to avoid it by just changing the name.

**Comment by bbatsov** [comment]
This was actually my second suspicion. :-) OK, I'll use some other name from the presentation as a workaround.

**Comment by bbatsov** [comment]
@Malabarba didn't you recently fix this?

**Comment by Malabarba** [comment]
I did. Not sure why I didn't tag the issue.
