### ISSUE TITLE
CIDER creates a bunch of *nrepl-messages [...]* buffers

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1458]
Latest CIDER:

![image](https://cloud.githubusercontent.com/assets/1006557/11683028/94d35d38-9e68-11e5-9cb7-217b720ab845.png)

**Comment by expez** [comment]
Most of these seem to contain only:

```
(<- 
  id  "13"
  out  "To quit, type: :cljs/quit\n"
  session  "22726a7d-0815-44a8-b716-5275b9e3419f"
)
```

With varying session id.

**Comment by expez** [comment]
New buffers are created when I run the [refactor-nrepl resolve_missing tests](https://github.com/clojure-emacs/refactor-nrepl/blob/master/test/refactor_nrepl/ns/resolve_missing_test.clj) in emacs.  

The boilerplate was copied wholesale from cider-nrepl so the same likely happens when those tests are run in emacs. 

 I'm not sure if this is expected or not, but at least this means this bug probably doesn't affect 'real' users.

**Comment by bbatsov** [comment]
Hmm, I wonder what's causing the creation of new sessions... At any rate - it would have been better if we aggregated the messages per connection instead of per session, but the logging code is an place where the connection is not directly available and fetching it by session requires some coupling to cider, which I wanted to avoid.

**Comment by cddr** [comment]
I get this as well just from normal usage.

**Comment by bbatsov** [comment]
I plan to fix this, but it requires a bunch of changes to the `nrepl-client.el`, which I don't have time to do right now - mainly passing the connection all the way down to the logging code.

**Comment by Malabarba** [comment]
@bbatsov What if we just keep the old behaviour (single buffer) by default, and have a custom var to get the new behavior (per-session buffers)? I'm happy with the "per-session" buffers, and I don't particularly feel the need to make them "per-connection".

Plus, this would take like 3 min to code. :)

**Comment by bbatsov** [comment]
Nope. There has to be some incentive to fix the fucked-up logging in a proper manner... Sessions logs were a bad idea (mostly because of the throwaway sessions we didn't anticipate), that's clear now - but we did it because it was an easier solution. I'm add fine with adding an option to merge the log into one buffer, but only when I get to aggregate all connection sessions together.

**Comment by Malabarba** [comment]
Alright then. :-)

**Comment by bbatsov** [comment]
I get your point, but I'm way too wary of quick fixes, that become permanent. I'll try to find some time for this by the end of the week.
