### ISSUE TITLE
Paredit and Curly braces in cider-repl-mode

### ISSUE THREAD

**Issue by jsrodrigues** [clojure-emacs/cider#1479]
I noticed that paredit mode for curly braces seems to be broken in the cider-repl. ```(add-hook 'paredit-mode-hook #'clojure-paredit-setup)``` in cider-repl.el does not fix the issue. I had to add the following lines in my emacs init file to fix this.
```
(add-hook 'cider-repl-mode-hook
          '(lambda ()
             (define-key cider-repl-mode-map "{" #'paredit-open-curly)
             (define-key cider-repl-mode-map "}" #'paredit-close-curly)))
```
```
Emacs Version: 24.5.1
Mac OS X: El Capitan
; CIDER 0.10.0 (Java 1.8.0_66, Clojure 1.7.0, nREPL 0.2.12)
```

**Comment by cichli** [comment]
Thanks for the report. I'd noticed this as well, and fixed it in the same way (you don't need to call `define-key` in the mode hook though, you can just call it at the top-level) - but forgot to file an issue :-).

The problem is that we call [`clojure-paredit-setup`](https://github.com/clojure-emacs/clojure-mode/blob/802c1dbf3529da5a09f97cb21833e0a27ccf41d7/clojure-mode.el#L232) when [enabling the mode](https://github.com/clojure-emacs/cider/blob/759b0866d168f6852a598f725eec422743cd8fa1/cider-repl.el#L1234), and this assumes that the keys should be set in the `clojure-mode` map - but `clojure-mode` is not active in REPL buffers (presumably it was at some point in the past).

I guess we can modify `clojure-mode` s.t. that function optionally takes a mode map - thoughts @bbatsov @Malabarba?

**Comment by Malabarba** [comment]
Sounds good.

**Comment by bbatsov** [comment]
Yeah, that sounds reasonable.
