### ISSUE TITLE
Add a print-method for atoms

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1496]
Filing this here mostly so I don't forget, but anyone is free to try it as it should be pretty trivial.

**Comment by seanirby** [comment]
I'd like to take a look, could you give some details?

**Comment by seanirby** [comment]
Oh, I see,that the work needs to be done in the cider-nrepl repo, not this one.

**Comment by seanirby** [comment]
Current print-method for an Atom is here:
https://github.com/clojure/clojure/blob/bc186508ab98514780efbbddb002bf6fd2938aee/src/clj/clojure/core_print.clj#L387-L408

Which looks like:
```
=> (println (atom {:foo :bar}))
#object[clojure.lang.Atom 0x54274a2b {:status :ready, :val {:foo :bar}}]
```
It looks like ':status' will always be ':ready' for an atom since atoms do not implement the "IPending" interface.  I propose we drop this information in the new print method since it's not useful.  New print output will look like the following:

```
=>(println (atom "{:foo :bar}"))
#atom[{:foo :bar} 0x54274a2b]
```

The identity hash code is moved to the end to keep it consistent with the print output for multifn.  Let me know what you think.

**Comment by Malabarba** [comment]
I think it looks nice. What do you think @bbatsov? Shall we ask for a PR?

**Comment by bbatsov** [comment]
Yep. I like it.

**Comment by bbatsov** [comment]
Fixed in https://github.com/clojure-emacs/cider-nrepl/pull/284
