### ISSUE TITLE
cider-result popup buffer resets the font size after every evaluation

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-emacs/cider#1547]
CIDER 0.10.1

If I increase the font of the `*cider-result*` buffer with <kbd>C-x C-+</kbd> with a new evaluation it loses the given size and reset to the default one.

**Comment by Malabarba** [comment]
Upon further thought, I don't think this is a bug. The results buffer intentially calls `(kill-all-local-variables)` because it's supposed to be “new”.
For instance, I see that Emacs `*Help*` buffers behave the same way.

You could increase the font-size globally, or restore the font-size every time the buffer is created by advising `cider--pprint-eval-form`.

**Comment by BrunoBonacci** [comment]
Thanks for taking the time to respond to this issue.
Could you please explain what you mean by 

>  by advising `cider--pprint-eval-form`??

**Comment by Malabarba** [comment]
Sorry it took me so long.
See if this works:


    (defadvice cider--pprint-eval-form (after increase-size)
      (text-scale-adjust 2))

**Comment by daveliepmann** [comment]
I didn't have success with that, but did with this:

```elisp
(defun dl/cider-result-scaler ()
  (text-scale-set 2))

(add-hook 'cider-popup-buffer-mode-hook #'dl/cider-result-scaler)
```

**Comment by bbatsov** [comment]
The reset is a consequence of how the popup buffers work - they're rebuilt from scratch on every evaluation (`kill-all-local-variables` and all), so anything buffer-local you set by hand goes away with the old buffer, text scale included. That's why `C-x C-+` doesn't stick.

The hook approach above is the right fix, since `cider-popup-buffer-mode` is re-enabled on each rebuild. If you'd rather not have it affect every CIDER popup (docs, macroexpansion, etc.), you can scope it to the result buffer:

```elisp
(add-hook 'cider-popup-buffer-mode-hook
          (lambda ()
            (when (equal (buffer-name) cider-result-buffer)
              (text-scale-set 2))))
```

Preserving the scale across rebuilds on CIDER's side would be doable if there's real demand, but the hook seems like the right home for what's ultimately a personal display preference.

**Comment by BrunoBonacci** [comment]
Thank you for getting back onto this issue.

The situation in which this issue came about was as following: I was making a presentation on a large screen, and I was asked to increase the size of the fonts as people at the back couldn't read  the text.

On one side I had a buffer with my code, the other side the pop-up buffer. I increased the size in both using `C-x C-+` but then noticed that after each evaluation the buffer was getting reset. I'm sure this used to work in oder releases, but I'm not sure when the change was introduced exactly.

- I understand that from a Emacs perspective the current behaviour is the correct one.
- The solutions proposed wouldn't work as increasing the font via `C-x C-+` is typically a temporary change, that's why, for my case, this solution is not adequate. 
- If the change is to be permanent it would be easier to change it globally once for all.
- I ended up increasing the font globally during the presentation, and I've been doing that every since. It would be nice if the text size was preserved, but I understand the reasons why you might not want to introduce this change.

thank you for looking into this.
