### ISSUE TITLE
Add support for running expectations

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1606]
An `expectation` works quite different from a `deftest`, so this will take some work.

- [ ] An expectation has no explicit name, so `cider-test-run-test` would need to work differently.
- [ ] Expectations undef themselves after being run, so `cider-test-run-ns-tests` would need to load the test file before each run.
- [ ] Because they don't expand to proper `deftest`s, it will take some work to integrate them with the test-report buffer.

**Comment by bbatsov** [comment]
That'd be great. Supporting midje would also be useful. I have a feeling that by supporting only `clojure.test` we're kind of killing the competition...

**Comment by Malabarba** [comment]
I have a feeling we're killing `cider-test`. :-)
Those command-line interfaces that automatically run tests when you save files are probably more popular than `cider-run-tests`.

**Comment by bbatsov** [comment]
@Malabarba you were supposed to figure out the perfect tdd-mode right? ;-)

**Comment by Malabarba** [comment]
Yes. That's stlll on the wait list, but it's getting closer.

**Comment by jeffvalk** [comment]
Two notes:

1. `cider-test` has progressively swallowed essentially all of the runner functions of `clojure.test`. It's compatible with the original, but it's essentially a re-implementation. If we wanted to do something different, we have free rein.

2. The `clojure.test` test protocol isn't perfect, but it is open. Any test library could implement it if so desired. For instance `test.check` does, and `cider-test` handles `defspec` just like `deftest`.

**Comment by Malabarba** [comment]
Yes. The annoying thing about expectations is that it does its own thing instead of working on top of deftest. So there's really no way to support it other than writing dedicated code for it. 

That said, even though I'm the one who filed this, it's very low on my priorities because I'm no longer using expectations.

**Comment by jeffvalk** [comment]
The `clojure.test` machinery is designed to be pluggable. There's nothing special about `deftest`. (All it does is add metadata to a var.)

So rather than twist `cider-test` to accommodate all the test libraries that might pop up, the better thing to do here would be submit a PR to the expectations (or midje or whatever) maintainer to support the built-in `clojure.test` machinery. It's pretty straightforward:

1. Assoc each test fn as `:test` metadata on some var. These are what get run.
2. Implement the `clojure.test/report` multimethod to capture the test results.

The `test.check` library is a good example here. It was also designed completely independently of `clojure.test`. It just adds compatibility in [this namespace](https://github.com/clojure/test.check/blob/24f74b83f1c7a032f98efdcc1db9d74b3a6a794d/src/main/clojure/clojure/test/check/clojure_test.cljc).

**Comment by bbatsov** [comment]
That's a pretty good point! I didn't even know you could use `test.check` with `cider-test`. :-)

**Comment by bbatsov** [comment]
I've added @jeffdik's remarks to the readme (in a slightly reworded form). I propose for us to just file a few issues to to the prominent Clojure test libraries describing this and see if they're interested in adding `clojure.test` compatibility.

**Comment by Malabarba** [comment]
Sounds good!  👍

**Comment by jeffvalk** [comment]
@bbatsov I updated that readme section to DRY it out.

And yeah, `test.check` support has always been there. It could present failed test results in more detail, but it certainly works!

**Comment by bbatsov** [comment]
:+1:

**Comment by bbatsov** [comment]
I've filed tickets for midje and expectations. Feel free to expand on my descriptions there.

**Comment by seancorfield** [comment]
I've taken a look at Expectations / `cider-test` today (since we rely on Expectations very heavily at World Singles and we also use CIDER) and it's fairly painful. For those who are interested, I added comments on my initial exploration here https://github.com/jaycfields/expectations/issues/70#issuecomment-237113313

Feedback welcome (on that ticket -- I'm only dropping it here to get eyeballs).
