### ISSUE TITLE
Test failure overlay is put on the wrong place if the assertion is not at the start of the line.

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1683]
Run this test:

```clojure
(deftest status
  (when (is (= 201 200))
    (do-something)))
```

The red overlay is placed on the `when`, not the `is`.

Similarly, on this situation:

```clojure
(deftest status
  (is (= 201 200)) (is (string? nil)))
```

The overlay is only placed on the first `is`.

**Comment by xiongtx** [comment]
This is due to the [rather simplistic logic](https://github.com/clojure-emacs/cider/blob/1ee97c4c4bbb9f7c8b6dffde0112cbb8338870dd/cider-test.el#L522-L527) in `cider-test-highlight-problem`.

However, given that `clojure.test` doesn't provide anything more than filename and line, it's hard to imagine how we can highlight the _right_ forms.

**Comment by bbatsov** [comment]
Isn't this a simple solution - we go to the right line and then we search forward for `is` or `are`.  Not bulletproof, but I think it will work pretty well most of the time.

**Comment by xiongtx** [comment]
There are several such macros besides `is` and `are`. We also won't know which one to highlight if there are several on the same line (2nd example above).

**Comment by bbatsov** [comment]
Yeah, that's true. That's why I said "most of the time". 😆 

I think we should probably send some patch to `clojure.test` adding the column information and see if they'd be willing to accept it.
