### ISSUE TITLE
Helm interface to CIDER

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#1693]
@bbatsov Can you create a `helm-cider` repository for me? I want to take a crack at addressing #1059 and #1541.

Better yet, can you give me the ability to create it myself?

**Comment by bbatsov** [comment]
> Better yet, can you give me the ability to create it myself?

Done. You've got the power! :-)

Btw, I was wondering if it won't be easier/more convenient to have such packages in a contrib folder of the main repo and just distribute them as separate packages on melpa. This would make updates easier and will make it harder for a package to go out of sync with cider. On the other hand - it will also make it impossible to release stable versions of these packages independently of cider and will also result in new snapshot builds on every cider commit (due to the way melpa works). Probably the separate repo approach is better as it's more flexible.

**Comment by xiongtx** [comment]
Actually, GitHub still says that I have insufficient permission to create a new repository.

![cider-1693](https://cloud.githubusercontent.com/assets/1624090/14667630/cb0e296e-06a5-11e6-8df6-88349e179532.png)

Putting projects in a `contrib` folder is the route that [SLIME](https://github.com/slime/slime/tree/master/contrib) has chosen to go, but SLIME's been around a lot longer and its contrib packages tend to be more stable. Maybe this would be a good idea if/when CIDER reaches maturity.

**Comment by bbatsov** [comment]
Try again. Seems I forgot to click "save settings". :-)

**Comment by xiongtx** [comment]
Thanks. I've created the [helm-cider](https://github.com/clojure-emacs/helm-cider) repository.
