### ISSUE TITLE
Request: let cider-refresh-after-fn accept a function with optional args

### ISSUE THREAD

**Issue by Peeja** [clojure-emacs/cider#1762]
Currently, `cider-refresh-after-fn` "must be a namespace-qualified function of zero arity." The function I'd like to call takes an optional argument, but I'd like to call it with the defaults. Unfortunately, Cider refuses because its arity isn't literally 0. It would be great for me if it would still call it with arity 0, as long as that's legal.

**Comment by bbatsov** [comment]
Yeah, I guess we can change this.

**Comment by dpsutton** [comment]
I'm not sure how to setup the nrepl client so that i can test this, but i believe that the following change should fix it in cider-nrepl/src/cider/nrepl/middleware/refresh.clj in the invoke-and-resolve function when checking the arglists:
`(some #(or (= % []) (= '& (first %))) (:arglists (meta #'f)))`

**Comment by dpsutton** [comment]
Pull request here [https://github.com/clojure-emacs/cider-nrepl/pull/365](https://github.com/clojure-emacs/cider-nrepl/pull/365)

**Comment by bbatsov** [comment]
This is merged now.
