### ISSUE TITLE
Make the scratch buffer work with cljs

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1789]
Rotating the connection should dispatch to the right buffer.  Alternatively we could add a cljs scratch buffer.

**Comment by bbatsov** [comment]
I'm not sure what exactly do you refer to. More details, please.

**Comment by expez** [comment]
Right now the scratch buffer just dispatches to the clj buffer and there's noting to be done about it.  Cljs users would like a scratch buffer too!

**Comment by bbatsov** [comment]
There's a command to set the connection used by the scratch buffer. Probably we can add something to directly create a cljs scratch or we can simply prompt at buffer creation time about the connection that should be associated with a scratch buffer.

**Comment by bbatsov** [comment]
See the changes I've made here - hopefully it's now clear how to change the buffer's connection.

**Comment by vspinu** [comment]
This connection hack (among quite some others) is essentially due to unavailability in cider of an intermediate construct between connection process/buffer and connection's project-dir. None of the currently available "connection" units corresponds to the much needed "interaction connection" or "eval connection".  

FYI, I started looking into refactoring the connection system and I am on the way to drop this change as well as the whole "default-connection & friends" hairdo in favor of a hopefully much simpler interaction model.

**Comment by achikin** [comment]
Looks like `cider-toggle-buffer-connection` command is not available.

**Comment by vspinu** [comment]
It has been removed with the new connection system. I think the best option would be to allow the scratch to be of various types *clj*, *cljs* and the default "cljc". You could choose the type with C-u on `cider-scratch` if you really need that.
