### ISSUE TITLE
cider-nrepl:jar:0.14.0-SNAPSHOT missing? 

### ISSUE THREAD

**Issue by vijaykiran** [clojure-emacs/cider#1816]
## Expected behavior
cider-jack-in should work.
## Actual behavior
Fails with 
`Could not find artifact cider:cider-nrepl:jar:0.14.0-SNAPSHOT in clojars (https://clojars.org/repo/)`
## Steps to reproduce the problem

- Update to latest packages in Emacs  (not the pinned packages)
- Open any clojure file 
- And M-x cider-jack-in

### CIDER version information
CIDER 0.14.0snapshot (package: 20160727.904)

### Emacs version
GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47) of 2016-07-25

### Operating system
 OS X 10.11 "El Capitan"

**Comment by Malabarba** [comment]
I haven't configure my clojars credentials here at work yet. But I can push the snapshot tonight if @bbatsov doesn't get to it first.

**Comment by dpsutton** [comment]
Is this an argument to switch to a more git-flow style of development? Since this was a commit on master, it allowed people to update on elpa. At work we work off of develop, and the only commits to master (aside from hot fixes) are releases. You can still merge develop into master periodically to give people snapshot builds, but it would prevent updates for each and every commit, and possibly broken ones like this?

**Comment by Malabarba** [comment]
However, this didn't happen because of some random commit. This happened because of [this commit](https://github.com/clojure-emacs/cider/commit/6f1527de786991a18abde4b7190bfe00b5c368eb) which specifically bumps the injected version to

**Comment by dpsutton** [comment]
Yeah. That's what I meant. It was a commit that was purely for devs, not to be released. But since it was on master many people saw an updgrade to cider and upgraded, rendering their cider packages broken. If this was done on the develop branch, no such release on melpa would have occured, and development for CIDER devs would have been unaffected.

**Comment by Malabarba** [comment]
@bbatsov just got distracted and forgot to do the same for cider-nrepl, which needs to be done at the same time regardless of our release workflow (he's a busy guy :-).
It's not a commit for developers, it's just a completely broken commit as is. :-)

**Comment by Malabarba** [comment]
Also, changing to a dev branch would sort of just reimplement the advantages of Melpa.
We have stable releases on Melpa-stable. Melpa is for snapshots and will break occasionally.

**Comment by bcarrell** [comment]
Until one of the maintainers pushes a new version to Clojars, keep in mind the workaround is to essentially:

```
git clone https://github.com/clojure-emacs/cider-nrepl.git
cd cider-nrepl
lein install
```

Hope that helps.

**Comment by expez** [comment]
https://clojars.org/cider/cider-nrepl/versions/0.14.0-SNAPSHOT

**Comment by Malabarba** [comment]
Thanks @expez. Good to know at least one of us hasn't forgotten how to push a clojar. :-)
