### ISSUE TITLE
[feature request] Command to load buffer into specific nREPL connection

### ISSUE THREAD

**Issue by aengelberg** [clojure-emacs/cider#1853]
When two `*cider-repl ...*` buffers are open, currently `C-c C-k` appears to make a best-effort attempt to load into the REPL started in the project that file belongs to. I'd like to be able to override that and load a file into a specific nREPL connection.

**Comment by bbatsov** [comment]
That's more complex than it sounds. You don't really want just one such command, you want every evaluation command to be able to act on a specific connection. That's why CIDER has a second mode which operates with the concept of a default connection and all evaluations get always dispatched to it. There are more details about this in the manual https://cider.readthedocs.io/en/latest/managing_connections/

**Comment by aengelberg** [comment]
Thanks for the link, I wasn't aware of the "display" and "rotate" functionality. I no longer need this feature.

**Comment by bbatsov** [comment]
Keep in mind `rotate` is only meaningful with `static` connection dispatch.

**Comment by bbatsov** [comment]
Btw, I've added one new command (`cider-toggle-request-dispatch`) to make it easier for people to temporary toggle between dynamic and static dispatch.
