### ISSUE TITLE
After changing `cider-boot-parameters`, CIDER refuses to inject dependencies.

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/cider#1871]
## Expected behavior
CIDER injects dependencies upon `cider-jack-in` even when `cider-boot-parameters` have been modified.

## Actual behavior
CIDER complains that `cider-boot-parameters` have been changed and does not inject the dependencies.

## Steps to reproduce the problem
Modify `cider-boot-parameters`.

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_101
```

### Lein/Boot version

Boot 2.6.0

### Emacs version

25.1

### Operating system

OpenSUSE Tumbleweed, FreeBSD 11.0

**Comment by bbatsov** [comment]
I don't quite understand what you mean. Injecting dependencies is controlled by a different defcustom.

**Comment by Malabarba** [comment]
Are you referring to this warning?

    Warning: `cider-boot-parameters' doesn't call the "repl" task, jacking-in might not work

What value did you set this variable to?

**Comment by zilti** [comment]
I've set the variable to `dev`. Jacking in works fine, I don't get warnings, but it doesn't inject the dependencies, and I get the classical version mismatch errors, also stating that "one possible cause" would be that cider-boot-parameters got changed (which is what I did).

**Comment by Malabarba** [comment]
That's odd, cider should give you the warning I pasted above. Maybe it got immediately replaced by another message. Do `C-h e` and see if you can spot that message in there. 

Anyway, the problem itself is not a bug, it's a limitation. Cider can only inject dependencies on the repl task. If you want to use a different task you have to either (i) define it so that it can be called in conjunction with the repl task, or (ii) add the cider plugin yourself (there are instructions on the manual). 

This limitation is supposedly lifted on an upcoming version of boot.

**Comment by zilti** [comment]
Ahh, I see. I supposed it'd get injected afterwards, so I didn't make that connection. Thanks!
