### ISSUE TITLE
Running `cider-eval-last-sexp` emacs reports the following error: Symbol's value as variable is void: hi

### ISSUE THREAD

**Issue by randre03** [clojure-emacs/cider#1900]
## Expected behavior
Evaluate the sexp

## Actual behavior
emacs reports the following error: `Symbol's value as variable is void: hi`

## Steps to reproduce the problem
Position the cursor at the end of the desired sexp to be evaluated and press C-x C-e (or M-x cider-eval-last-sexp)

### CIDER version information
```
;; CIDER 0.15.0snapshot (package: 20161224.925), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_66
```

### Emacs version
Emacs version: GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F34)) of 2016-05-25

### Operating system
Mac OSX Sierra 10.12.2

**Comment by xiongtx** [comment]
What sexp are you evaluating?

**Comment by randre03** [comment]
No matter what sexp I try to evaluate I get this error..namespaces, defs, defns, etc

**Comment by dpsutton** [comment]
I think I've seen this bug pop up before. It should be fixed by removing
and installing CIDER. However, you post a full stack trace? I've seen this
pop up every now and then (I think) and I'd like to know how it happens

On Dec 26, 2016 7:21 PM, "Roger Randall" <notifications@github.com> wrote:

No matter what sexp I try to evaluate I get this error..namespaces, defs,
defns, etc

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/clojure-emacs/cider/issues/1900#issuecomment-269254608>,
or mute the thread

**Comment by randre03** [comment]
Thanks. Deleting and re-installing did the trick. If I recall correctly, when I installed it the first time around (using paradox) after selecting "Install" in the buffer the buffer updated and indicated there was an obsolete version of cider to install and I think I clicked to install that as well. This could easily have caused the problem I think.
