### ISSUE TITLE
cider-toggle-buffer-connection fails

### ISSUE THREAD

**Issue by alvinfrancis** [clojure-emacs/cider#1913]
## Expected behavior

`cider-toggle-buffer-connection` should toggle between CLJ and CLJS connections (if both exist) in a `clojurec-mode` buffer (e.g. `cljc` files) or in a `cider-clojure-interaction-mode` buffer (e.g. `*cider-scratch*`).  This should allow expressions to be evaluated in the appropriate connection. Also, `cider-connections` should still contain both CLJ and CLJS connections after toggling.

## Actual behavior

Connection to REPL is seemingly lost; evaluating expressions causes CIDER to complain that a Clojure REPL is required and that a jack in is probably needed.  Also, `cider-connections` loses one of the connections (the current one).

## Steps to reproduce the problem

1. Do `lein new cider-toggle-buffer-connection`
2. Edit `project.clj` to the following:
``` clojure
(defproject cider-toggle-buffer-connection "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [com.cemerick/piggieback "0.2.1"]
                 [org.clojure/clojure "1.7.0"]]
  :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
  )
```
3. Do `mv src/cider-toggle-buffer-connection/core.cljs src/cider-toggle-buffer-connection/core.cljc`
4. Edit `src/cider-toggle-buffer-connection/core.cljc` to the following:
``` clojure
(ns cider-toggle-buffer-connection.core)
(println "Test")
```
5. Open `src/cider-toggle-buffer-connection/core.cljc` in emacs.
6. Do `cider-jack-in-clojurescript`.
7. Take note of the value of `cider-connections`: there should be two connections (CLJ and CLJS).
8. Evaluate `(println "Test")` with `cider-eval-last-sexp`.  This should print "Test" in the `*cider-repl cider-toggle-buffer-connection*` buffer.
9. Do `cider-toggle-buffer-connection`.
10. Evaluate `(println "Test")` with `cider-eval-last-sexp`.  This should cause CIDER to complain with the following message:
> user-error: ‘cider-eval-last-sexp’ needs a Clojure REPL.
If you don’t know what that means, you probably need to jack-in (‘C-c M-j’).
11. Take note of the value of `cider-connections`: only the CLJS connections remains.

### CIDER version information

```
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_74
```

### Emacs version

> GNU Emacs 25.1.3 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47) of 2016-09-18

### Operating system

OSX 10.11.6

**Comment by alvinfrancis** [comment]
@dpsutton

**Comment by bbatsov** [comment]
@dpsutton did you end up looking into this?

**Comment by dpsutton** [comment]
Something to note: the reported behavior is not correct. When eval-ing code in a cljc buffer under `cider-jack-in-clojurescript`, the default behavior is to eval the code in *both* connection buffers. So the observed behavior from `(println "Test")` is that both repls print "Test". After toggling, you were stuck inside of only a single connection.

This happens because the toggling worked by setting a buffer local `cider-connections` to hide the regular list of connections. When grabbing the `cider-other-connection`, it did not consult the original list but the truncated list and was therefore unable to find the other connection.

Now the behavior is
1. eval -> "Test" in both buffers
2. toggle
3. eval -> "Test" in clj buffer
4. toggle
5. eval -> "Test" in cljs buffer
5. toggle with prefix
6. eval -> "Test" in both buffers
