### ISSUE TITLE
Better handling of elaborate spec definitions in doc buffer

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1914]
Currently the specs in the doc buffer are on a single line.  When you're writing a spec for a multi-arity function this can make them unreadable in the doc buffer.

**Comment by bbatsov** [comment]
//cc @cskksc

**Comment by cskksc** [comment]
I haven't been using Clojure a lot in the past few months. I guess that's why I never noticed it. How does this look ? 

![2017-01-12-132652_1276x743_scrot](https://cloud.githubusercontent.com/assets/5201497/21902697/e703d112-d8ca-11e6-84c8-c8045215177a.png)

Right now, I'm just formatting the outermost sequence so that each member is displayed on its own line. Do you expect the individual members to be long as well ? If so, we just have to recursively process every member.

**Comment by cskksc** [comment]
I guess the `ret:` and `fn:` should also be aligned. I'll include that in this patch.
