### ISSUE TITLE
Provide cider function to find all known impls of a protocol function

### ISSUE THREAD

**Issue by dball** [clojure-emacs/cider#1969]
I like to use protocols to define coherent boundaries in my application, but they make it impossible to use cider-find-var and friends to navigate from call site to implementation. It would be awesome, and doesn't seem conceptually difficult, if cider provided a function to navigate to all known implementations of a protocol function.

**Comment by dpsutton** [comment]
I'd like to tackle this but i don't know of a good starting off point if anyone has any suggestions.

**Comment by bbatsov** [comment]
I think you'll need a middleware that checks for:

* the protocol of the function at point
* all loaded records that implement a certain protocol
* present a list with the results the user so they can make their pick

In general this issue is an opportunity to do more for working with protocols in CIDER - I can imagine that functionality that shows you quickly which protocols does a type implements would be quite useful, also functionality that shows you all types implementing some protocol, some search for available by protocols by method name, etc. All this should be pretty easy to implement once the foundational middleware is created.

**Comment by harold** [comment]
Is this done now? Or should it be reopened? Or is there another issue that covers this functionality?

**Comment by bbatsov** [comment]
Yeah, that's done.

**Comment by harold** [comment]
🆒 !
