### ISSUE TITLE
`cider-browse-spec-navigation` is always `nil`

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#2036]
## Expected behavior

`cider-browse-spec-navigation`'s stated purpose is to keep track of the spec browser navigation stack. However, it is always `nil`.

## Actual behavior

`cider-browse-spec-navigation` is always `nil`. This prevents functions like `cider-browse-spec--print-curr-spec-example` from working correctly.

## Steps to reproduce the problem

1. View a spec that uses another spec in its definition via `cider-browse-spec`
2. Navigate to the other spec (by clicking on it)
3. See that `cider-browse-spec-navigation` remains `nil`

### CIDER version information

Commit ff4c0ed9bc70c3f48ad74d08c9f7c97e91b2553c.

**Comment by bbatsov** [comment]
Hmm, probably I broke this my making it buffer-local. I was under the impression this was state for the browser buffer, but it's actually a state spanning the spec display buffers as well. 

Seems to me this browser functionality encompasses things that have nothing to do with the the browser-mode itself and this creates some confusion (I certainly didn't expect something named this way to behave as it does).

**Comment by bbatsov** [comment]
Yeah, I'm right. I didn't pay much attention when I was reviewing the code, but it uses the same mode to renders specs and to display the spec listing, which seems pretty confusing to me, as would never expect such a behaviour - there should probably be some `specview-mode` similar to the `docview-mode`. I'll revert my change, but using global state for something like this is definitely a problem. The moment you start working on two projects this would break down completely. The solution would be for the specview buffers to have some buffer-local variable and just to rerender themselves instead of creating new buffers (which is probably what's the causing the problem now). I'll investigate it more if I have some time.

**Comment by xiongtx** [comment]
I agree that the spec overview should be a different major mode from the individual spec view.

As mentioned in #2035, it makes for sense for the spec browser to behave like `cider-docview-mode`, i.e. derive from `help-mode` and take advantage of that familiar, built-in functionality.

> The moment you start working on two projects this would break down completely.

Does `cider-docview-mode` handle this any better? I was not under that impression.

>  I didn't pay much attention when I was reviewing the code

<img src="https://imgflip.com/s/meme/Thats-a-paddlin.jpg" width="200" />

**Comment by bbatsov** [comment]
> Does cider-docview-mode handle this any better? I was not under that impression.

There's just one such buffer at any time, so you can't really run into a problem with it. For the browser I can assume you might be browsing a few different projects.

**Comment by xiongtx** [comment]
I'm pretty sure the spec browser puts everything into a single buffer as well--both the top-level view and the individual spec views.

**Comment by bbatsov** [comment]
> I'm pretty sure the spec browser puts everything into a single buffer as well--same buffer for both the top-level view and the individual spec views.

Yeah, that's the current case, but I don't think it should be.
