### ISSUE TITLE
Can cider-jack-in-clojurescript enhanced to auto update build script?

### ISSUE THREAD

**Issue by shaqtsui** [clojure-emacs/cider#2103]
I see cider-jack-in support auto update build script to avoid manually modify the build script.
Can the same for cider-jack-in-clojure?

**Comment by bbatsov** [comment]
I'm not quite sure what you mean by this. Can you be more specific?

**Comment by xfcjscn** [comment]
To run command cider-jack-in, I don't need to modify project.clj to include cider-nrepl plugin, cider will modify it for me.
But to run command cider-jack-in, I need to manually modify project.clj to include: :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}.
I think this modification can be done by the command not by application developer

**Comment by bbatsov** [comment]
Ah, now I get it - yeah, this certainly can be done. Even now you can just update something like `cider-jack-in-dependencies` to achieve this. 

I guess it was an oversight of ours that we didn't add some preconfigured deps to be injected for the various types of ClojureScript projects.

**Comment by vspinu** [comment]
There is an option to clojure jack-in first and then to bootstrap the clojurescript repl. In such case one would need an explicit declaration I presume.

**Comment by vemv** [comment]
I'm not sure this is worthwhile at the moment. The cljs ecosystem is quite heterogeneous.

For simple projects and that use Piggieback (unlike shadow-cljs, a notably popular choice today) you might be able follow:

> Even now you can just update something like cider-jack-in-dependencies to achieve this.

Otherwise it seems most advisable to follow the given build tool's instructions. CIDER docs will also help you for the most popular choices.
