### ISSUE TITLE
Improve the way cider-jack-in-clojurescript works

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2202]
Current `cider-jack-in-clojurescript` is very problematic, as it doesn't really do any attempts to figure out what's the best ClojureScript repl to start for the users project - it just uses a configurable init form to boot the repl, that's mapped to a project type (lein, boot, etc). While this makes sense for `cider-jack-in`, it doesn't make (almost) any sense for ClojureScript as most of the cljs repls are not tied to build tools at all. We need to do several things to improve the current situation:

* probe which of the potential repls are supported by the users current environment (e.g. by checking whether their namespaces are bound) and offer the user to select one of them
* add some function to determine which of the supported repls is the most capable to suggest it as the default (e.g. if figwheel's supported, we should probably go with it, on boot projects we should probably go with the boot cljs repl, etc)
* add some defcustom just jack-in straight to the default repl (useful for lazy people who are fine with the detection mechanism)

That's a pretty simple, but important task on our way to better cljs support IMO. //cc @gonewest818 @ckoparkar @xiongtx @dpsutton

**Comment by mrrodriguez** [comment]
I discussed this on Slack #cider with @dpsutton and putting it here for additional visibility.
One issue I brought up with the current ClojureScript integration in Cider is that it is awkward and brittle to set the `cider-cljs-lein-repl` because you have to set it to the entire code form string that is used in Cider.

For example, in my Emacs config for this, I have something like:
```elisp
;; Set to the required key in cider.el const `cider--cljs-repl-types`
(setq cider-cljs-lein-repl
      "(do (require 'figwheel-sidecar.repl-api) (figwheel-sidecar.repl-api/start-figwheel!) (figwheel-sidecar.repl-api/cljs-repl))")
```

I'd like to be able to set the type to "figwheel" and it know the invocation required for that rather than setting it to the actual invocation.

**Comment by bbatsov** [comment]
@mrrodriguez That's already changed on `master`. See https://github.com/clojure-emacs/cider/blob/master/cider.el#L550

**Comment by mrrodriguez** [comment]
Thanks @bbatsov I'll have to check that out soon then.

**Comment by vemv** [comment]
Things are fairly refined and decoupled by now
