### ISSUE TITLE
Issue jacking in clojurescript in spacemacs

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2278]
## Expected behavior
Both clj and cljs repls start after `cider-jack-in-clojurescript`
## Actual behavior
cljs repl does not start
## Steps to reproduce the problem
This issue appears after `clojure-mode` was updated to the latest version.
Open Spacemacs, navigate to clojure project and run `cider-jack-in-clojurescript`
The following error has been found in `*Messages*`
```
[nREPL] Establishing direct connection to localhost:58864 ...
[nREPL] Direct connection to localhost:58864 established
Connected.  Unfortunately, no one can be told what CIDER is. You have to figure this out yourself.
error in process filter: cider-cljs-repl-form: Symbol’s function definition is void: nil
error in process filter: Symbol’s function definition is void: nil
```
### CIDER version information
```
CIDER 0.17.0snapshot (package: 20180430.444), nREPL 0.2.13
Clojure 1.8.0, Java 1.8.0_20
```
### Lein/Boot version
```
Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM
```
### Emacs version
```
GNU Emacs 25.3.1
```
### Operating system
```
macOS High Sierra
Version 10.13.4
```

**Comment by dpsutton** [comment]
@achikin there should be a prompt asking which type of cljs connection you want to run. If you are not seeing this, maybe you have set that var? If this is what you are doing, the way you specify which type has recently (changed)[https://github.com/clojure-emacs/cider/commit/a2534bfdeb8f574e4fb4cc8b3697be8606f126f3]. Now instead of `"figwheel"` as a string you use `'figwheel` as a symbol. Can you check if this is perhaps what you are seeing?

**Comment by achikin** [comment]
@dpsutton I had the variable set to string, exactly as you said. Thank you!
