### ISSUE TITLE
Associating projects with connections using cider-connect

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2380]
I guess this is partially an issue, partially a question to @vspinu. I played a bit with `cider-connect`, while working on `lein-nrepl` and I noticed that after you use `cider-connect` sesman doesn't link the the project root of the file you visited when you ran `cider-connect` (and didn't prompt you for what to link to, which you have been ideal IMO). Is this an oversight? How are you supposed to use this exactly now?

**Comment by vspinu** [comment]
It's a bug then. cider-connect should work as jack-in in this regard. That is, assoc with the project or dir by default and ask on C-u. I will check this up.

**Comment by bbatsov** [comment]
On a general note - there should be a simpler way to see what context a REPL is associated with. Generally "Show links" doesn't give me the overview I hoped it will. And from time to time you can get weird results like:

![image](https://user-images.githubusercontent.com/103882/43095715-6730fc24-8ebf-11e8-8fa1-55bc4d5def11.png)

Btw, I also noticed the "Show Session" doesn't handle deleted REPL buffers properly.

**Comment by vspinu** [comment]
> Generally "Show links" doesn't give me the overview I hoped it will

Yeh, there is plenty of room for improvement here, but it's all about naming sessions. In the snapshot `~` is the name of the session, which currently is just the project direcory. Any concrete suggestions or requirements regarding the session names that you could think of?

> Btw, I also noticed the "Show Session" doesn't handle deleted REPL buffers properly.

I am aware of this but I wasn't too eager as yet with implementing automatic dead-buffer cleaning in order to avoid obscuring other bugs.

**Comment by bbatsov** [comment]
Well, I was imagining that we'd have something like the connection browser you removed that shows all sessions and nested under them their connections and some context information. I think the session names themselves should be just "session-type/context(context-type)" or something like this. 

I think the context type would be quite useful as it'd be hard to tell if something's linked to a project dir or some random dir (for instance).

> I am aware of this but I wasn't too eager as yet with implementing automatic dead-buffer cleaning in order to avoid obscuring other bugs.

Fair enough. Not a big deal, but it's something to keep in mind. 

Btw, I also saw this from message from @plexus:

> It seems `cider-connection-browser` disappeared in the latest version, not sure many people were using it but I used it all the time, so I hacked together a replacement.

https://github.com/plexus/plexmacs/blob/master/sesman-table/sesman-table.el

Seems I'm not the only person frustrated with the current UI. :-)

**Comment by jumarko** [comment]
+1 for "connection browser". Especially useful when there's no connection associated with a current project but you have a bunch of other projects opened and some of them have associated session.

**Comment by vspinu** [comment]
> Well, I was imagining that we'd have something like the connection browser you removed that shows all sessions and nested under them their connections and some context information. 

To see all connections and associations use C-c C-s C-i.  On C-u it shows all linked sessions and with `C-u C-u` it shows all sessions regardless of the associations. Connection browser hardly can add anything essential to this display and is, thus, not a high priority. 

> I think the session names themselves should be just "session-type/context(context-type)" or something like this.

This doesn't make sense. Session doesn't have type and each session can be linked to multiple contexts. 

> I also saw this from message from @plexus:

Nice. But it presumes cider in requires (@plexus why?). I think such a table should be generic. I personally see helm-style interface more natural, so maybe this functionality should not be part of sesman proper in the first place.

**Comment by plexus** [comment]
> Connection browser hardly can add anything

I disagree, I tried `C-c C-s C-i`, it just prints some stuff in the minibuffer, there is no interaction. I use the connection browser to kill connections, I often end up with a half a dozen connections. Being able to get a visual overview and `k`ill them is very handy.

> it presumes cider in requires (@plexus why?)

It uses `cider-popup-buffer-display`. This is a personal hack that I'm sharing for those that miss the connection browser. It is provided as-is. It's GPL, folks are welcome to run with it.

**Comment by bbatsov** [comment]
I also tried the built-in functionality and it's completely useless to me. I can hack something together for sesman, if @vspinu doesn't want to do it, but my hands are full between CIDER and the nREPL updates and this will have to wait. 

> To see all connections and associations use C-c C-s C-i. On C-u it shows all linked sessions and with C-u C-u it shows all sessions regardless of the associations. Connection browser hardly can add anything essential to this display and is, thus, not a high priority.

I'd expect that I could change contexts there, kill sessions, etc. Classic Emacs stuff. To me that's a lot of value. 

> This doesn't make sense. Session doesn't have type and each session can be linked to multiple contexts.

But you do want to know what it's linked to when you're interacting with it... That makes a lot of sense to me. I certainly want to make sure it's linked to the right context. Obviously this only makes sense for file backed buffers, it's not a concern for REPLs and similar.

**Comment by vspinu** [comment]
> I also tried the built-in functionality and it's completely useless to me.

I don't know how it could be "completely useless" if what you propose is a simple duplication of the existing functionality in the sesman map. I think you are not yet used to the concept. 

I would suggest that before building new functionality people have to first figure out what is exactly missing and why current tooling is insufficient. 

> I'd expect that I could change contexts there, kill sessions, etc. Classic Emacs stuff.

All stuff is already in the sesman map and the "connection buffer" will not be able to duplicate all of the functionality from there anyhow. For example it's impossible to implement satisfactory linking from a "connection buffer" because you would need to provide completions for projects and directories. Would work for buffers though. It's also not straightforward to provide refined control on individual connections because sesman has not access to that functionality. Plus, tabular displays are just not good enough for the task at hand; one could have 5+ connnections per sessions and fitting that into a table cell is not the the best idea. A hierarchical approach would be needed. Anyways, a few things to think about before "hacking something together". 

> But you do want to know what it's linked to when you're interacting with it...

Yes. And this is what C-c C-s C-i and C-c C-s C-l are for. Plus mode-line should display current session, but that's a different feature which still has to be implemented.

**Comment by vspinu** [comment]
> I use the connection browser to kill connections, I often end up with a half a dozen connections.

This one is hard to make generic as the notion of objects composing a session is required. Let me think a bit about that. Maybe a good solution would be for C-c C-s C-i to bring up an interactive buffer where actions on individual connections are provided as text properties and are specific to the system at hand. I will check your implementation.

**Comment by vspinu** [comment]
@bbatsov 
> And from time to time you can get weird results like: `directory(~/) -> ~`. 

How about a more explicit `directory(~/) -> ses(~)` ? REPL names could look something like `*ses(dir-name):cljs:node*`. The idea is to use same naming convention throughout.

**Comment by vspinu** [comment]
I suggest to close this issue in favor of:

  - #2392 for new session and REPL buffer names scheme
  - vspinu/sesman#5 for session browser implementation
  - vspinu/sesman#8 for UI simplification and enhancement 

Regarding the OP, sessions are associated with projects automatically. It's just the legacy info display confusingly says <no project> because it's still not aware of the sesman sessions. I will remove/rewrite that part within a few days.
