### ISSUE TITLE
The clojure executable isn’t on your ‘exec-path’ on Windows

### ISSUE THREAD

**Issue by didibus** [clojure-emacs/cider#2424]
## Expected behavior

Given a clojure-mode buffer.
Given we have no project.clj
When running cider-jack-in
Then we are connected to an empty standard Clojure REPL

## Actual behavior

We are instead greeted with the following error: `user-error: The clojure executable isn’t on your ‘exec-path’`, and cider does not start a repl and does not jack-in.

## Steps to reproduce the problem

`C-x b`  into a new buffer.
`M-x` clojure-mode to switch major mode to clojure.
`M-x` cider-jack-in

## Environment & Version information

0.300.0@26.1 (spacemacs)

### CIDER version information

CIDER 0.18.0-snapshot

### Emacs version

26.1

### Operating system

Windows 10

**Comment by dpsutton** [comment]
hi @didibus this seems most likely a problem with your setup. I think a simple remedy is to add lein to your path. You can do this inside of emacs as well with

```lisp
(add-to-list exec-path "lein/path")
```

**Comment by bbatsov** [comment]
The actual problem here is different - since CIDER 0.17 repls outside projects are started using `clojure ...` instead of `lein repl`. But I don't think that the `clojure` script is present on Windows, so we should probably make the default command selection a bit smarted and check if `clojure` is present, falling back to `lein`.

**Comment by 4lph4-Ph4un** [comment]
Hi! As the windows support for clj is looming and I've started to work on few projects that unfortunately are scafolded around clj instead of lein, what's the stat with this? 

I seem to have similar issue to above, which I believe is rooted into to the fact that current windows clj is mainly run through PowerShell. Any suggestions for some workarounds for the time being?

https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows
