### ISSUE TITLE
ClojureScript doc has link to outdated REPL overview

### ISSUE THREAD

**Issue by pbwolf** [clojure-emacs/cider#2432]
http://www.cider.mx/en/latest/clojurescript/ says "There are many ClojureScript REPLs out there and it's often hard to wrap your head around them and the differences between them. You'd do well to read _this awesome article_...", a link to https://lambdaisland.com/guides/clojure-repls/clojurescript-repls.  

The linked page describes Rhino as the current built-in ClojureScript REPL.  It also describes Austin, whose Github page says the last commit was Feb. 1, 2015.  

The link no longer supports the goal of a non-confusing high-level orientation to ClojureScript REPLs.  If, amidst the historical detail, something awesome is there that I need to know in order to grok CIDER then please mention it directly in Cider's documentation.

**Comment by bbatsov** [comment]
Hmm, I think that the article mentions that Austin was superseded by Weasel and that Nashorn is also-built-in, but I see your point. I'll think how exactly to approach this and I'll also ping @plexus in case he's interested in this feedback (as the author of that particular article).

**Comment by plexus** [comment]
Thanks for the feedback. The repl guide is open to contributions through GitHub. It has gradually been getting out of date, and unfortunately giving it a big refresher has not been high enough on my list of priorities, especially since the repl guide on clojure.org by @vvvvalvalval is now available as a more practical guide to Clojure repl use. But PRs are of course very welcome, no matter how small.

I didn't know the cider docs linked to it, I agree it would be better for the docs to be self contained.
