### ISSUE TITLE
CIDER + aggressive-indent interrupts typing (Quit)

### ISSUE THREAD

**Issue by nikolavojicic** [clojure-emacs/cider#2457]
When both CIDER and aggressive-indent-mode are enabled, typing gets interrupted very often with the 'Quit' message shown in the minibuffer.

Works fine:
- Enabled CIDER + disabled aggressive 
- Disabled CIDER + enabled aggressive

[Emacs config files](https://github.com/nikolavojicic/.emacs.d)

**Comment by vspinu** [comment]
Please `M-x toggle-debugger-on-quit` and let us know the traceback. I am using aggressive indent but have never seen this issue.

**Comment by bbatsov** [comment]
Likely it's a similar issue to https://github.com/clojure-emacs/cider/issues/2281

Using aggressive-indent on bigger files can be problematic because of many expensive calls to `clojure-project-dir` (now cached in `clojure-mode`) and `clojure-find-ns`. I failed with caching the latter properly in `clojure-mode` and this has to be revisited at some point (see https://github.com/clojure-emacs/clojure-mode/issues/480). I guess that disabling dynamic-font-locking should solve the problem in the mean time. 

For me, personally, aggressive-indent was pretty slow even in big Elisp files, that's why I stopped using it a while back.

**Comment by nikolavojicic** [comment]
With `toggle-debugger-on-quit` I get this error:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```
Or sometimes just this: 
`Debugger entered--Lisp error: (quit)`

More info from debugger [here](https://gist.github.com/nikolavojicic/8d0b64b20ef17599cbf1c3f87db496c2).

Also, debugger was triggered few times when I scrolled using mouse.

File .clj is not that large - cca 200 LOC.
Removing `cider-font-lock-dynamically '(macro core function var)` didn't help.

**Comment by dpsutton** [comment]
just to make sure, @nikolavojicic do you happen to have `clojure-toplevel-inside-comment-form` set to `t`? I've seen a slowdown with this in the past. Just making sure we are investigating the right part.

**Comment by nikolavojicic** [comment]
@dpsutton nope, it's nil. You can find my exact setup [here](https://github.com/nikolavojicic/.emacs.d).
I gave up aggressive-indent-mode, so just revert [these changes](https://github.com/nikolavojicic/.emacs.d/commit/9dbb3e1941d5786a9c5eba64d1d17694d5604f2b).
Using emacs-26.1-x86_64 on Windows 7.
