### ISSUE TITLE
option to call `cider-undef` automagically when deleting a `def` or `defn`

### ISSUE THREAD

**Issue by borkdude** [clojure-emacs/cider#2639]
When removing something like `(defn foo [])` from a buffer, I often forget to call `cider-undef` followed by `foo`.

It would be handy if there was a configuration option that causes, when deleting code from the buffer, `cider-undef` to be called automagically.

**Comment by Malabarba** [comment]
I think something like that would be a little too magical to have a reasonable implementation. 

One alternative option would be for cider to undef all vars in a namespace automatically when you load-file (`C-c C-k`) in that namespace. This has to make some assumptions that are true most of the time (like the fact that each file corresponds to a namespace) so it has to be opt-in, but other than that it should work well.

**Comment by borkdude** [comment]
@Malabarba That could be an idea (@bbatsov proposed the name `cider-sync-buffer`) for that on Twitter:  https://twitter.com/bbatsov/status/1132337425987117064.
However, doing that, I would lose vars I defined in a `comment` for debugging, so that's not fine-grained enough for me.

**Comment by Malabarba** [comment]
Cool to see I just basically suggested the idea you had already thought of. :rofl: 
I agree with your point, but I don't know of a better option. :man_shrugging:

**Comment by borkdude** [comment]
@Malabarba Before we close this issue out of a lack of good alternatives, maybe it's good to explicitize why it might be too magical?

**Comment by Malabarba** [comment]
We don't have to close the issue, I'm just giving my opinion. :-) Someone else might think it's more approachable.

-----

To answer your question:
Basically, there's an infinitude of ways you can edit the code in Emacs such that the result removes or changes a `def*`. The only solution that comes to mind that could cover everything would be to hook into `before/after-change-hooks`, figure out whether any valid `def*` forms have been removed by change and call `cider-undef` on those.

That, however, would have a series of corner-cases that might not behave how the user would expect (which would have to be manually worked around or left as a surprise for the user :-) ). Here are a few I can think of:

- You could move the form to a different part of the buffer via cut and paste. That involves a deletion, but people might not expect that to undef the var.
- You could accidentally type a character in the form, causing `def` to become `adef`. Even if you immediately hit `undo`, that'll undef the var because for a moment that wasn't a def form.
- Say you want to copy the var name to paste somewhere else. I usually do a quick cut+undo on the var name to copy, but that would undef the var.


None of this means we can't have the feature. It just means if we go this route the author will have to decide whether to work around these cases or to document them.
