### ISSUE TITLE
Dynamic font locking breaks in ClojureScript if requiring too many namespaces

### ISSUE THREAD

**Issue by oskarkv** [clojure-emacs/cider#2675]
## Expected behavior

Dynamic font locking always works.

## Actual behavior

Dynamic font locking breaks for ClojureScript if requiring too many namespaces. At least I think that requiring too many namespaces is the problem, but I'm not 100% sure. See for example the following screenshot, where removing `specter` from the require list makes font locking work again.

![Screenshot](https://i.imgur.com/1aW4sXr.png)

I tried it with regular Clojure too, but the problem didn't seem to happen there. I tried adding a lot of namespaces but the font locking never broke.

## Steps to reproduce the problem

The following works for me. Download https://github.com/oskarkv/fontlocking and `cider-jack-in-cljs`, then `cider-load-buffer`. The symbol `ffff` in `fontlocking.core` is not font locked. Remove a few namespaces from the `ns` form, and `cider-load-buffer` again. Font locking now works for `ffff`.

### CIDER version information

Cider commit edbbbd889ce9dfa446c912f21ab5b2f42fbf0f7a

```
;; CIDER 0.22.0snapshot (package: 20190607.2013), nREPL 0.6.0
;; Clojure 1.10.1, Java 12.0.1
```
### Emacs version

25.2.2

**Comment by bbatsov** [comment]
That's pretty weird - I can't imagine why more data would cause this to stop working. I'll take a look when I can, but anyone's welcome to beat me to this. :-) //cc @Malabarba

**Comment by oskarkv** [comment]
Keep in mind that I'm not 100% sure that the problem is too many namespaces, but it seems that way.

**Comment by Malabarba** [comment]
Instead of "too many namespaces" I think it's more likely that requiring `specter` is causing the problem.

Could you test something?

- Create a cljs file.

**Comment by Malabarba** [comment]
IIRC, the dynamic font-locking code is full of safeguards to make sure it shuts-off silently when there are any errors.

Instead of "too many namespaces" I think it's more likely that requiring `specter` is causing the problem.

Could you test something?

- Create a cljs file without requires.
- Define a function in it
- Use this function in it
- Verify that dynamic font-locking works.
- Add a require for specter.
- Does the font-locking stop working?


If that's the case, it's probably some metadata that's getting sent by nrepl which Emacs doesn't know how to read for some reason (possibly because cider-nrepl is not escaping something properly).

**Comment by oskarkv** [comment]
@Malabarba I have done this. It's not only requiring specter that breaks it. In fact, it can break without specter. At a certain point, when requiring a lot of namespaces, any additional namespace required seems to break it.

**Comment by Malabarba** [comment]
Alright, then I guess your initial idea is right. :-)

Could ir be that nrepl has a limit of how much  data it can send in one request? Though I'm not aware of that.
