### ISSUE TITLE
Invalid version syntax for -SNAPSHOT

### ISSUE THREAD

**Issue by hlolli** [clojure-emacs/cider#2746]
## Expected behavior

Cider starts normally with cider-jack-in with snapshot versions of Clojure.

## Actual behavior

Cider throws an error

```
Debugger entered--Lisp error: (error "Invalid version syntax: ‘1.11.0-master-SNAPSHOT’")
  signal(error ("Invalid version syntax: ‘1.11.0-master-SNAPSHOT’"))
  error("Invalid version syntax: `%s'" "1.11.0-master-SNAPSHOT")
  version-to-list("1.11.0-master-SNAPSHOT")
  version<("1.11.0-master-SNAPSHOT" "1.8.0")
  cider--check-clojure-version-supported()
```

## Steps to reproduce the problem

1. Clone the clojure repository
2. Build a jar with current master with `mvn package`
3. Add that file to deps.edn with `org.clojure/clojure {:local/root "/path/to/clojure-1.11.0-master-SNAPSHOT.jar"}`
4. open a source file and run in emacs `cider-jack-in`.

## Environment & Version information

```
$ uname -a
Linux hlolli 4.19.79 #1-NixOS SMP Fri Oct 11 16:21:44 UTC 2019 x86_64 GNU/Linux
```

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:41761
;; CIDER 0.23.0snapshot (package: 20190926.701), nREPL 0.6.0
;; Clojure 1.11.0-master-SNAPSHOT, Java 11.0.3-internal
```

### Emacs version

`GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)`

**Comment by dpsutton** [comment]
```

**Comment by bbatsov** [comment]
Seems that the built-in `version-to-list` function can't handle Clojure's weird versioning scheme for its SNAPSHOT. I'm surprised they've put `master` into the version. Guess we can check for this manually and strip `master` from the version or something like this.

**Comment by dpsutton** [comment]
Stripping seems fragile. And releases should be safely parseable. If you're using a more custom Clojure its most likely advanced and not too old so this check is brittle and almost always a false positive. It should really just warn when seeing Clojure 1.6 or below.

**Comment by bbatsov** [comment]
You mean 1.7 and lower. :-) But for the comparison to work you need to extract the version numbers - you can't do a string comparison as 1.10 will be less than 1.7 there.

**Comment by dpsutton** [comment]
I agree with you that the versions aren't comparable if they include master. My thinking was that in the case that they do, they are more likely newer rather than too old so they most likely won't fail the version check. And stripping master out now works but we don't know what the artifact names might include going forward. It just sounds like a recipe for weird false positives to me.

and i thought 1.7 was still supported :)

**Comment by bbatsov** [comment]
It hasn't been supported for a while now. I don't recall why exactly, probably something to do with ClojureScript.

**Comment by lread** [comment]
The versioning scheme for maven artifacts is quite flexible.  

While recently trying to figure out what might be legal (or not) [in creating a patched version of clojure 1.10 for use with GraalVM](https://github.com/lread/clj-graal-docs/tree/master/CLJ-1472#build-clojure-with-1472-patchsh), I found [Maven versions explained](https://octopus.com/blog/maven-versioning-explained) useful.

For what its worth, [my bash regex](https://github.com/lread/clj-graal-docs/blob/ef067e70f999e2bca5b0c8e73df4d61a0550c6a1/CLJ-1472/build-clojure-with-1472-patch.sh#L85).

**Comment by lread** [comment]
Might not have to get too fancy?

Given a minimum version of `1.8.0`, these concrete examples would all be considered below the minimum version:

* `1.8.0-master-SNAPSHOT` <- yep, this was a possibility [even back then](https://github.com/clojure/clojure/commit/eb26aac312b9f5a754bd639193fbd225e1ff4342#diff-600376dffeb79835ede4a0b285078036L8)
* `1.8.0-RC3`
* `1.8.0-alpha2`
* `1.8.0-beta1`

If we are comfortable assuming that:

* Clojure versions will continue with major.minor.patch with optional qualifiers.
* Cider min Clojure version will always be an official release.

For Clojure, we can consider version `1.8.0-anyqualifiers` to be less than version `1.8.0`.

And because min versions are in the past, Cider can always adapt if Clojure changes the scheme in the future.

Of current interest to me is the patched versions of Clojure I am generating to overcome GraalVM issues.  An example of a Clojure `1.10.1` patched version is `1.10.1-patch_38bafca9_clj_1472_3`.  (Technically my patched version would be considered earlier than version `1.10.1` - and that should be considered a flaw in my patch version scheme rather than something Cider would special case.)  As long as Cider doesn't barf on parsing a Clojure version with qualifiers I'd be good.

**Comment by benjamin-asdf** [comment]
I still get a warning because I have `Clojure 1.11.0-master-SNAPSHOT` does somebody have a good workaround for this?

**Comment by bbatsov** [comment]
Probably we should implement the suggested fix to remove everything after the version digits. As a workaround you can override the problematic function in your `init.el`.

**Comment by bbatsov** [comment]
Oh, well - let me just fix this now. That's more effective than discussing a workaround here. :-)
