### ISSUE TITLE
Cider debugger can't instrument certain `recur` forms

### ISSUE THREAD

**Issue by yuhan0** [clojure-emacs/cider#2772]
## Expected behavior
Successfully use the debugger on forms that include a `loop/recur`

## Actual behavior
```
Syntax error (UnsupportedOperationException) compiling recur at (repro.clj:7:8).
Can only recur from tail position
```

## Steps to reproduce the problem

Eval the following form
```
#dbg
(loop [i 0]
  (case i
    10 (recur (inc i))
    :halt))
```

Note: there is no indication of what form exactly is not in tail position and causing the issue. Different combinations of `(recur)` and base cases inside the `case` form either throw the same error or eval successfully, without an obvious correlation. 

Eg. the following works:
```
#dbg
(loop [i 0]
  (case i
    10 (recur (inc i))
    (recur i)))
```

Manually macroexpanding a form with `#dbg` reveals nothing different from an uninstrumented form.

### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20190708.1036), nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_192
````

### Emacs version

26.3

### Operating system

macOS 10.14

**Comment by FiV0** [comment]
So I dived a bit into the debugger. The above PR fixes the issue above, but there are still problems with `recur` and the debugger. The problems mainly come from this line. 

https://github.com/clojure-emacs/cider-nrepl/blob/8a7ae731fdbc25ff53e15de0dff61c8ca4969c6f/src/cider/nrepl/middleware/util/instrument.clj#L181

At this line the debugger actually decides whether an instrumented breakpoint should actually be applied or not. If the considered form contains a `recur`, but no `loop` or `fn` the breakpoint is ignored, otherwise the form can't be compiled as `recur` is not a tail-position. This is not a big deal most of the time, but in some cases it breaks the whole debugger if the `#break` or `#dbg` statement is not at the toplevel. Consider the following example:
```clj
(loop [i 0] 
  #dbg {:break/when (= i 7)}
  (when (< i 10)
    (println i)
    (recur (inc i))))
```
After the breakpoints have been instrumented the above statement *should* look something of the following form (I am simplifying a lot to get the point across):
```clj
(loop*
 [i 0]
 (#'cider.nrepl.middleware.debug/breakpoint-with-initial-debug-bindings
  (if
   (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
    (<
     (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
      i
      {:coor [2 1 1]}
      i)
     2)
    {:coor [2 1]}
    (< i 2))
   (do
    (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
     (println
      (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
       i
       {:coor [2 2 1]}
       i))
     {:coor [2 2]}
     (println i))
    (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
     (recur
      (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
       (inc
        (#'cider.nrepl.middleware.debug/breakpoint-if-interesting
         i
         {:coor [2 3 1 1]}
         i))
       {:coor [2 3 1]}
       (inc i)))
     {:coor [2 3]}
     (recur (inc i)))))
  {:coor [2]}
  (when (< i 2) (println i) (recur (inc i)))))
```
The macro `breakpoint-with-initial-debug-bindings` sets up the STATE__ variable used in other potential breakpoints. This macrocall is currently avoided because of the line mentioned at the beginning, but the other interesting breakpoints are still expanded and try to reference the STATE__ variable and hence the error `Unable to resolve symbol: STATE__ in this context`. In case one replaces the `#dbg {..}` with  a simple `#break` the above would only contain a single `breakpoint-with-initial-debug-bindings` which are currently not applied and hence nothing happens. 

There are two options to solve this:
1. We simply check if the `#break/#dbg` statement is just in front of a form containing in a `recur` and without a `loop` and issue a warning to the user that this won't have any effect.
2. Whenever there is `#break/#dbg` nested somewhere we wrap the whole toplevel expression in a call that sets up the debug bindings thereby fixing the `unable to resolve STATE__` issue and the breakpoints are still applied as usual either recursively (`#dbg`) or just once (`#break`). This would at least solve the `#dbg` issue. In case of a `#break` just before a form containing a `recur` we could push the `#break` inside the first form. So  
```clj
(loop [i 0] 
  #break
  (when (< i 10)
    (println i)
    (recur (inc i))))
```
would actually become something like (expanded ofcourse)
```clj
(loop [i 0] 
  (when #break (< i 10)
    (println i)
    (recur (inc i))))
```
The second solution is of course nicer but also more work and we need to do kind of two passes on the code to see if we need the toplevel debugger bindings. I hope this all makes sense. Let me know your thoughts and I might look into it.

**Comment by bbatsov** [comment]
Thanks for diving into this, @FiV0! My strong preference would be see if we can implement the second approach you've suggested. I don't think the additional pass on the code is a big deal - robustness is definitely more important. 

@Malabarba @vspinu Input from you is welcome as well.

**Comment by vspinu** [comment]
Thanks a bunch @FiV0. Unfortunately I am completely useless these days and cannot help, but your second proposal surely makes sense to me. So basically you suggest to add the STATE form not at the #dbg statement but just outside the `loop` if detected, right?

**Comment by FiV0** [comment]
@vspinu That is correct. Always setup the state around the whole toplevel expression.

**Comment by vspinu** [comment]
Always? I think that was the case originally and I changed it to local for, I hope, good reason. Don't recall the details unfortunately. By blaming and looking for my commits you might be able to figure out the reason. Maybe it's simple like this: top level is often not the expression executed, we need dynamic STATE not the state at instrumentation time.

**Comment by FiV0** [comment]
You are right. These were the respective threads.
https://github.com/clojure-emacs/cider/issues/2453
https://github.com/clojure-emacs/cider-nrepl/pull/544
Will look into this tomorrow.

**Comment by FiV0** [comment]
So because of the issue with `deftype` mentioned just above, the global setup is not an option. I tried to decouple the STATE setup from the breakpoint logic and that works to some extent (`#dbg` without a conditional just before a form ending in `recur` works).  But the way the conditional breakpoints are currently setup it's not possible to push them deeper into the instrumented form. I guess the interleaving breakpoints via macroexpansion comes to it limits in this case.

**Comment by Malabarba** [comment]
Yes, the whole situation is sort of delicate. The macro implementation is also not super-well suited to the idea of backtracking above the debug macro (macros are meant to handle what's inside them).

Unfortunately I don't have a good solution for it. 
We could just implement a message telling the user something like "expression X can't be debugged because it would remove the recur from tail position"

**Comment by bbatsov** [comment]
@Malabarba I like this idea! An informative message would be a nice improvement over the current situation.

**Comment by FiV0** [comment]
@bbatsov @Malabarba I think to get something really robust, one would need to rewrite the debugger. I think something using [https://github.com/clojure/tools.analyzer](url) would be nice because then we could maybe do clj/cljs in one go, but that is, I guess, subject for another thread.

**Comment by bbatsov** [comment]
> I think something using https://github.com/clojure/tools.analyzer would be nice because then we could maybe do clj/cljs in one go, but that is, I guess, subject for another thread.

There are different parsers for Clojure and ClojureScript and you'd still have the problem of not being able to evaluate ClojureScript. 

While the current debugger is not perfect I really like its simplicity and the fact it's almost language agnostic (Emacs's Elisp debugger is structured very similarly). But I'm always open to discussing better options, especially if someone's willing to work on them. :-) Anyways, that's definitely a topic for another ticket.

**Comment by Malabarba** [comment]
Sadly, I'm not sure if tools.analyzer would help here. The hard part about debugging cljs is not reading the code (that part will probably work with small adjustments). The hard part is making the runtime interaction work between nrepl and the client, because it relies heavily on locking while it waits for a response.

**Comment by bo-tato** [comment]
I just ran into this issue also. I'm doing some advent of code problems to learn clojure:
https://gist.github.com/bo-tato/0446e2f8a1de272e0a02e09b6c7179f9
The four positions there where #break is inserted have no effect. And if you change any of the #break to #dbg you get a compile error: `Unable to resolve symbol: STATE__ in this context`
At list this is documented know here: https://docs.cider.mx/cider/debugging/debugger.html#caveats
But maybe the messaging could be improved, giving a warning in the case of a #break that has no effect, and giving a better error message in case of #dbg.

Also in general the debugger works great, if using cider-eval-defun-at-point, but although there are plenty of #break and #dbg in the code, if using cider-eval-buffer the debugger never runs.

**Comment by bbatsov** [comment]
@bo-tato Feel free to open a new ticket about this. Sadly, we have been short on maintainers and bandwidth lately and the debugger has stayed mostly unchanged in the past few years.
