### ISSUE TITLE
cider-eldoc: wrong-number-of-arguments

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#2875]
## Expected behavior

CIDER and ElDoc play nicely together.

## Actual behavior

![backtrace](https://user-images.githubusercontent.com/8199224/87021987-279d3e00-c1d6-11ea-956c-36c16d2ef293.png)

(I had to take a screenshot because moving point results in the Backtrace window to disappear.)

## Steps to reproduce the problem

- Get and build Emacs master, commit `ef8bd7d8561be7ae2749127606bc40eed421601e`
- <kbd>M-x toggle-debug-on-error</kbd>
- Install CIDER (I use `straight`, but regular install via `package.el` and MELPA should be the same)
- Visit a new `.clj` file of your choice
- Write `(defn`

### CIDER version information

```
;; CIDER 0.26.0snapshot, nREPL 0.8.0-alpha3
;; Clojure 1.10.1, Java 11.0.7
```

### Lein/Boot version

Leiningen 2.9.3 on Java 11.0.7 OpenJDK 64-Bit Server VM

### System information

GNU Emacs 28.0.50

Master branch commit:
  ef8bd7d8561be7ae2749127606bc40eed421601e
  Update tests for recent changes

Configured with the following options:
  --host=x86_64-debian-linux-gnu
  --with-modules
  --with-imagemagick
  --with-harfbuzz

Running on:
  Ubuntu 20.04 LTS
  GNOME Shell 3.36.1 (x11)
  GTK+ Version 3.24.18, cairo version 1.16.0

**Comment by bbatsov** [comment]
I assume they changed something upstream recently, as this works fine with Emacs 26.3.

**Comment by bbatsov** [comment]
From your backtrace I can see that some hook is calling `cider-eldoc` with some arguments, even though the function accepts none.

**Comment by manuel-uberti** [comment]
Weird, there is no explicit usage of `cider-eldoc` in my configuration.

**Comment by manuel-uberti** [comment]
Inspecting Emacs code, I see in `/usr/local/share/emacs/28.0.50/lisp/progmodes/python.el` this:

```emacs-lisp
(defun python-eldoc-function (&rest _ignored)
...
```

Which is then added then to `eldoc-documentation-functions`:

```emacs-lisp
(add-hook 'eldoc-documentation-functions #'python-eldoc-function nil t)
```

Should `cider-eldoc` adopt a similar signature with regards to its arguments?

**Comment by bbatsov** [comment]
Yeah, probably. I wonder what this additional parameter is about.

**Comment by manuel-uberti** [comment]
From the docstring of `eldoc-documentation-functions`:
```
...
Each hook function is called with at least one argument CALLBACK,
a function, and decides whether to display a doc short string
about the context around point.
...
```

**Comment by manuel-uberti** [comment]
Actually, there is another possible signature. See, for instance, `elisp-eldoc-var-docstring` in `elisp-mode.el`:
```emacs-lisp
(defun elisp-eldoc-var-docstring (callback &rest _ignored)
...
```

**Comment by manuel-uberti** [comment]
I see @joaotavora pushed some ElDoc-related commits on `master`. Probably he can shine a light on this for us. :)

**Comment by joaotavora** [comment]
Yes, cider is using the unreleased variable `emacs-documentation-functions` that exists only in the upcoming Emacs 28, it is _not_ in Emacs 27.  As such, the protocol is considered unreleased, and subject to change.  You can safely make `(defun cider-eldoc (&rest _ignored) ...)` to fix this issue.

Beware that, again, that protocol is still consider _unreleased_ and subject to change (though I personally hope it will not change much).

If you'd like to know what these changes are and how they can potentially help Cider, let me know.

**Comment by bbatsov** [comment]
> Yes, cider is using the unreleased variable emacs-documentation-functions that exists only in the upcoming Emacs 28, it is not in Emacs 27. As such, the protocol is considered unreleased, and subject to change. You can safely make (defun cider-eldoc (&rest _ignored) ...) to fix this issue.

Yeah, I'm aware of this. The only reason CIDER uses it is that some users were running Emacs from Git and eldoc broke for them. 

> If you'd like to know what these changes are and how they can potentially help Cider, let me know.

That would definitely be useful. I'm assuming some changes will be needed down the road to take full advantage of it.

**Comment by joaotavora** [comment]
> Yeah, I'm aware of this. The only reason CIDER uses it is that some users were running Emacs from Git and eldoc broke for them.

Yes, I read https://github.com/clojure-emacs/cider/issues/2816

However, that should not have happened: Emacs 28 should _still_ support the old protocol, the one where you set `eldoc-documentation-function`.  I can't quite understand why the reporter reported that. Maybe it was a transient situation? Anyway merging the reporters' suggestion brought along the risks that we are now experiencing.

> That would definitely be useful. I'm assuming some changes will be needed down the road to take full advantage of it.

There's no manual yet, but reading the NEWS entries and the docstrings of the new functions would frame the issue for context.  Anyway, here's my summary.

In extensions such as SLIME, etc, that rely on external processes or sources, doc-gathering is best done asynchronously, not synchronously.  Otherwise, there will be a significant delay while the external process responds, especially if it takes a networking request.  Summarily, the new framework ensures that `cider-eldoc` can work asynchronously (if it does not do so already) and call the `CALLBACK` function when it's ready (perhaps in a process filter).  Eldoc will take it from there.

This is particularly useful if you attempt, in CIDER, to compose "at-point" documentation from a variety of sources.  This is what the plural "functions" in `eldoc-documentation-functions` means:

- Before my changes, this variable already existed, but it could not handle asynchronous sources: either a source computed the docstring immediately and produced it as a function return value, or it was ignored;

- After my changes, sources can now remain synchronous or become asynchronous with no impact to the previously established behaviour.

So, each time the cursor rests on a place long enough, you can have one CIDER source for variable documentation, another for function documentation, another for spell checking, another from Flycheck annotations, Flymake, etc, etc, you name it.

The new Eldoc can collect and gather documentation from all these sources and compose them together in a buffer.  Then, a short summary (a one-liner if the user so prefers) is echoed in the Echo area, whic is the familiar Eldoc behaviour.  This is controlled by the new variable `eldoc-documentation-strategy` which teaches Eldoc _how_ to compose the various sources, and `eldoc-echo-area-use-multiline-p`.

The latter part is still under construction: it is likely that the large buffer and the echo area are just two of an very large collection of possible "outlets" for documentation.  One can think of tooltips, frames, windows or other "on-line" displays for the information.

**Comment by bbatsov** [comment]
> So, each time the cursor rests on a place long enough, you can have one CIDER source for variable documentation, another for function documentation, another for spell checking, another from Flycheck annotations, Flymake, etc, etc, you name it.

That's certainly a welcome change. CIDER's backend is async, but Emacs is not very async friendly, so I had to emulate sync behavior for things like eldoc and completion (for instance). That being said - I guess Emacs 28 is not getting shipped any time soon, as we're still waiting for Emacs 27. :-) 

> The new Eldoc can collect and gather documentation from all these sources and compose them together in a buffer. Then, a short summary (a one-liner if the user so prefers) is echoed in the Echo area, whic is the familiar Eldoc behaviour. This is controlled by the new variable eldoc-documentation-strategy which teaches Eldoc how to compose the various sources, and eldoc-echo-area-use-multiline-p.

Sound pretty cool!

> The latter part is still under construction: it is likely that the large buffer and the echo area are just two of an very large collection of possible "outlets" for documentation. One can think of tooltips, frames, windows or other "on-line" displays for the information.

I think one of the bigger weaknesses of Emacs today is that there's no standard API for inline documentation - the kind that combines prototypes with docs and maybe even basic examples. I saw there's something like this in `lsp-mode`, but it'd be nice if eventually eldoc had support for this "modern" style of displaying docs, as many people are expecting it. I'm old school and for me it's all the same, but I know a ton of people are complaining about this. I've been doing some hacks with overlays in CIDER about this, but it's nowhere as nice as what you'd get in most other editors.

**Comment by manuel-uberti** [comment]
Thank you for the fix, @bbatsov, and thank you @joaotavora for the clarification.

The fix is working for me, so I guess we can close this ticket now.

**Comment by bbatsov** [comment]
I didn't close the ticket right away, because I was thinking of potentially removing this change for Emacs 28 as suggested by @joaotavora. Anyways, not a big deal.

**Comment by joaotavora** [comment]
> That being said - I guess Emacs 28 is not getting shipped any time soon, as we're still waiting for Emacs 27. :-)

Indeed, indeed.  But, there is hope! Eldoc, and many other files/packages like project.el, xref.el, flymake.el within the Emacs master branch, are now being distributed independently as packages in the GNU ELPA repo.  These are known as GNU ELPA `:core` packages.  Which means that you hack on them in the Emacs master repo, tag them with a version, and use them in Emacs < 28.   Just see elpa.gnu.org to see what's available, and declare `Package-requires` in your package.  This is a game changer, IMO, with a couple of small downsides:

- that backward compatibility is not always necessarily maintained as strictly as it for major Emacs versions (as I warned you earlier).  So in this case it might happen that the protocol for `eldoc-documentation-functions` changes again, potentially backward incompatibly.  We try to avoid that of course.
- the files can't use any functionality that is only available in Emacs master, otherwise that will break when they are loaded in previous Emacs versions.

Apart from this, I agree with all the rest that you said.

**Comment by joaotavora** [comment]
> I've been doing some hacks with overlays in CIDER about this, but it's nowhere as nice as what you'd get in most other editors.

It'd be very nice to see you move these hacks into something that can be added to `eldoc-display-functions`. Though I've not designed that variable yet (maybe you can help?)
