### ISSUE TITLE
Cider/Emacs crashes on throwing Exceptions with very large exception message

### ISSUE THREAD

**Issue by behrica** [clojure-emacs/cider#2936]
## Expected behavior

Cider should have a way to "limit" / truncate very large Exception messages, similar to using `cider-print-quota`

## Actual behavior
Evaluation this in Repl or source code buffer makes Emacs crash:

```clojure
(throw (Exception. (apply str  (repeat 10000000 "a")))
```
## Steps to reproduce the problem

1. start emacs
2. run `(setq cider-print-quota 10000)`
3. run `(setq cider-repl-buffer-size-limit 10000)`
4. execute above

-> Cider will print the full exception message into the Repl and Emacs is unresponsive and need to be killed.

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; Connected to nREPL server - nrepl://localhost:34565
;; CIDER 1.0.0snapshot, nREPL 0.8.2
;; Clojure 1.10.1, Java 11.0.8
```

**Comment by behrica** [comment]
By looking at the code here:

https://github.com/clojure-emacs/cider/blob/ef47c1de151c212b8d2ddeb9af6c8b0dfc0e300f/cider-stacktrace.el#L813

It seems to be indeed the case, that the Exception message itself is never truncated or size checked,
could potentially become arbitrary large and get printed in full, and therefore crashing Emacs.

I saw the issue in an exception coming from Spark, which put the whole column data in the exception message.

Eventually the problem could be as well fixed very localized, by truncating the exception message to a reasonable, configurable, size.

**Comment by tekacs** [comment]
I'm running into this issue myself -- I'm just commenting to keep this thread alive (given the stale bot above).

Happy to jump in and see if there's a way to make sense of this.

**Comment by bbatsov** [comment]
If you someone wants to work towards a solution - they are more than welcome to do so. This issue is definitely not on my todo list (as it seems to have fairly low impact), so I'd appreciate help with it.

**Comment by tekacs** [comment]
I'm happy to @bbatsov -- one question in doing so is:

You previously made obsolete the following definitions:

```elisp
(make-obsolete 'cider-stacktrace-print-length 'cider-stacktrace-print-options "0.20")
(make-obsolete 'cider-stacktrace-print-level 'cider-stacktrace-print-options "0.20")
(make-obsolete-variable 'cider-stacktrace-print-options 'cider-print-options "0.21")
```

But in turn it looks like message printing simply uses `insert` (or at the very least, message printing doesn't necessarily go to `cider-print-fn`, presumably since it's a pretty printer which would be overkill for a string-y message).

To propose a few different ways of solving this issue:

1. I could try to use `cider-print-fn` to output the messages to try to benefit from `cider-print-options` as the `make-obsolete` suggests, although I think `insert` is used for precise positioning so I can't say that I know immediately how to make sure they're put in the right place using this method.
1. I could (re-)introduce a limit on the size of the message printed? I didn't want to do this without asking, since you've explicitly made those `stacktrace-print-length` `defcustom`s obsolete in the past.

Would either of these seem palatable to you?

**Comment by tekacs** [comment]
I'm happy to @bbatsov -- one question in doing so is:

You previously made obsolete the following definitions:

```elisp
(make-obsolete 'cider-stacktrace-print-length 'cider-stacktrace-print-options "0.20")
(make-obsolete 'cider-stacktrace-print-level 'cider-stacktrace-print-options "0.20")
(make-obsolete-variable 'cider-stacktrace-print-options 'cider-print-options "0.21")
```

But in turn it looks like message printing (in `cider-stacktrace-emit-indented` and `cider-stacktrace-render-cause`) simply uses `insert` on the message passed back by `cider-nrepl`.

At the very least it seems that message printing doesn't necessarily go to `cider-print-fn` despite the above obsolete-s, presumably since it's a pretty printer which would be overkill for a string-y message.

To propose a few different ways of solving this issue:

1. I could introduce a limit on the size of the message printed? I didn't want to do this without asking, since you've explicitly made those `stacktrace-print-length` `defcustom`s obsolete in the past.
1. I could presumably try to use `cider-print-fn` to output the messages and/or try to benefit from `cider-print-options` as the `make-obsolete` suggests. This seems impractical though, as `message` is elisp-side rather than Clojure-side.

There seem to be two printers -- one is limited by the above, one prints to the REPL itself.

Would either of these seem palatable to you?

[0]: on a separate note, the `eldev` setup for hacking on Cider was an absolute joy to use -- it took me less than 5 minutes from reading your message about fixing this to debugging and finding references at the line where printing occurs -- I wish more projects made it so practical to contribute!

**Comment by tekacs** [comment]
So after playing with this a little, the following :override advice and buffer size limit seems to prevent Emacs from crashing.

This only limits the size of the message in the `cider-stacktrace` popover buffer and /not/ in the REPL itself (even though `cider-repl-buffer-size-limit` is set). Clearing the REPL after this removes the mass of text from the REPL and restores performance to normal.

For anyone else looking in on this:

- `cider-stacktrace` uses `:message` to print below (which is why we're limiting it successfully here)
- ... somewhere else, the value `err` from the response to `{:op :eval}` is being printed directly into the REPL buffer, causing the large amount of text there.

All I've done here is add `truncate-string-to-width` to the message return value to test whether that's the main cause (and as I mentioned, this at the very least prevents Emacs from spinning indefinitely).

```elisp
(defun my-cider-stacktrace-render-cause (buffer cause num note)
    "Emit into BUFFER the CAUSE NUM, exception class, message, data, and NOTE."
    (with-current-buffer buffer
      (nrepl-dbind-response cause (class message data spec stacktrace)
        (let ((indent "   ")
              (class-face 'cider-stacktrace-error-class-face)
                 (message-face 'cider-stacktrace-error-message-face))
          (cider-propertize-region `(cause ,num)
            ;; Detail level 0: exception class
            (cider-propertize-region '(detail 0)
              (insert (format "%d. " num)
                      (propertize note 'font-lock-face 'font-lock-comment-face) " "
                      (propertize class 'font-lock-face class-face)
                      "\n"))
            ;; Detail level 1: message + ex-data
            (cider-propertize-region '(detail 1)
              (if (equal class "clojure.lang.Compiler$CompilerException")
                  (cider-stacktrace-render-compile-error buffer cause)
                (cider-stacktrace-emit-indented
                 (propertize
                  (truncate-string-to-width (or message "(No message)") 100)
                  'font-lock-face  message-face)
                 indent t))
              (insert "\n")
              (when spec
                   (cider-stacktrace--emit-spec-problems spec (concat indent "  ")))
              (when data
                (cider-stacktrace-emit-indented data indent nil t)))
            ;; Detail level 2: stacktrace
            (cider-propertize-region '(detail 2)
              (insert "\n")
              (let ((beg (point))
                    (bg `(:background ,cider-stacktrace-frames-background-color :extend t)))
                (dolist (frame stacktrace)
                  (cider-stacktrace-render-frame buffer frame))
                (overlay-put (make-overlay beg (point)) 'font-lock-face bg)))
            ;; Add line break between causes, even when collapsed.
            (cider-propertize-region '(detail 0)
              (insert "\n")))))))

(advice-add 'cider-stacktrace-render-cause :override #'my-cider-stacktrace-render-cause)
(setq cider-repl-buffer-size-limit 10000)
```

**Comment by tekacs** [comment]
I also discovered that this isn't the issue that I'm personally having which is causing my Emacs to hang -- so I'll have to look into that separately. :)
