### ISSUE TITLE
Add support for UNIX socket connections

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3032]
Support for UNIX socket connections was recently added to nREPL 0.9 (currently in beta). We should make it possible to connect to UNIX sockets from CIDER.  This will require some changes to the connection functions (mostly in `nrepl-client.el`). We can either expose a `socket` param there directly or recycle `host` if it looks like a file name.

**Comment by bbatsov** [comment]
@rlbdv, btw is this something you plan to tackle? I was just reminded you're an Emacs user. :D

**Comment by bendlas** [comment]
I did a proof of concept, that let me successfully connect to a unix domain socket: https://github.com/bendlas/cider/commit/03675162be3d30624563718cd4030d035c1ac780

```sh
clj -R:nrepl-latest -m nrepl.cmdline --socket /tmp/clj.sock
```

```el
(cider-connect-unix (list :socket-file "/tmp/clj.sock"))
```

Not sure about how to best integrate this into the menu structure of cider though ...

**Comment by bbatsov** [comment]
Cool!

I think the bigger question is how to integrate this in the existing connect command, so we don't have to add new commands and create more confusion with them. Perhaps the current command can just prompt for socket as well as host and port and do something differently if there's a socket? I'll have to think a bit about this, but if anyone has great ideas - please, share them. :-)

//cc @vspinu

**Comment by bbatsov** [comment]
I left a bit more feedback on your commit.

**Comment by bendlas** [comment]
I'd be more than happy with a version, that only implements `cider-connect` support.

My use case is about developing in a VPN, and were it not for the REPL port, I could run my dev server in a completely isolated (linux) networking ns. Thus, cider-jack-in and other convenience isn't applicable anyway.

I suspect that many other use cases for domain- instead network-sockets will be similarly advanced.

**Comment by rlbdv** [comment]
Fair enough, and thanks for working on it.

**Comment by bbatsov** [comment]
Okay, guess we're on the same page, though. @bendlas Feel free to submit a PR when you're happy with your draft.

**Comment by bendlas** [comment]
Sure, I could use some help with the design for `cider-connect`, though.

nrepl doesn't seem to write `.nrepl-port` for socket servers, so auto-finding the socket seems out of scope for this for now.

How do you feel about this design:

- Instead of `Host:`, `cider-connect` prompts for `TCP Host or Protocol:`, and allow to enter `nrepl+unix:` (with auto-completion).
- If host/protocol is `nrepl+unix:`, it prompts for `Socket File:` instead of `Port:`
- If host/protocol is `nrepl:`, it would continue with prompting for `Host:` and `Port:`, as it currently does.

My self-assessment for this:

- it's consistent with the url format, that `nrepl.cmdline` prints
- does the overloading of the first prompt go far enough? Could/should we already accept full connection urls, like `nrepl://localhost:37013` or `nrepl+unix:/tmp/clj.sock`?

**Comment by bbatsov** [comment]
Btw, any chance you'll find some time for this in the next couple of weeks? CIDER 1.2 is close to release and it'd be nice to include this there.

**Comment by bendlas** [comment]
I could make time, since I'm still in need of this (currently I'm doing a somewhat ugly workaround involving `socat`).

Still getting a bit of a mixed vibe about the menu design.

Going back to your first suggestion, how about the following design:

- Instead of `Host:`, prompt for `Host or Socket file:`
- If input parses as a file and exists, try to connect via domain socket
- Otherwise continue with current flow (`Port:`, connect, ...)

**Comment by bbatsov** [comment]
Let's go for this as the simplest change that can work. If there's a file named like a hostname - we treat this as a file. Seems relatively unlikely and people can always use the IP in some case as a workaround.

**Comment by bendlas** [comment]
I took a stab at this yesterday and I'm rather confident that this change would actually be more complicated and that's because of auto-completion: Files are usually read with `read-file-name` and that's what things like `ido` would hook in to. The cider host is being read with a custom `completing-read`. I'd rather avoid trying to combine the semantics there.

The simplest change that I can see to make this work right now would be:

- designate and auto-complete a special hostname similar to `localhost`, e.g. `local-unix-domain-socket`
- when that hostname is entered, read a socket file instead of a port

that way, there would still be a potential clash (the special hostname), but with a much reduced surface and I feel that this would make the menu reasonably straightforward

If that's not what we want to do, I'd also be happy to just contribute the connection code and let somebody else figure out the menu.

**Comment by bbatsov** [comment]
I've got a simpler idea - if we use a prefix command now `cider-connect` prompts for all connection params. Perhaps we can just add `protocol` there and afterwards dispatch based on this. I'd also be down with a dedicated command, just to have some way for people who want to use this to use it. I can tackle this myself down the road, but I doubt it will happen in the next couple of weeks.

**Comment by bendlas** [comment]
That sounds like it could be made to work. Although there may still be some complications with adapting the history. Right now, there is a  `string-split` on `:` https://github.com/clojure-emacs/cider/blob/75755b42fac1efac9828b3326915907adf3690ff/cider.el#L1452

How would we migrate this from a previous version?

**Comment by bbatsov** [comment]
Let's figure everything else and worry about this later. :-) But one way that comes to mind is to simply pass the history via a conversion function every time its read. I guess that would be simplest approach.

**Comment by bendlas** [comment]
OK, I pushed what I currently have with the overloaded hostname `local-unix-domain-socket`.
I can continue with the explicit protocol parameter later, but that feels like almost a separate ticket.

**Comment by bendlas** [comment]
Just FYI, I'd consider [this CCE on newer JDKs](https://github.com/nrepl/nrepl/issues/245) a blocker for this feature, because it will cause a failure on connecting via file socket, and so this repo is likely to get reports for it.
