### ISSUE TITLE
A way to optionally elide noisy print near image in repl

### ISSUE THREAD

**Issue by harold** [clojure-emacs/cider#3033]
I am using CIDER in the production of some videos, and the capability to print images in the repl is amazing!

However, they come together with the noisy output I've highlighted in this screenshot:
![image](https://user-images.githubusercontent.com/7443/131061529-47cae239-8eb2-4ed0-bd42-817db298a3fa.png)

I'd like a way to disable that text output, at least temporarily, to avoid distraction in the video output.

Is this already possible?

I've considered hacking CIDER to suppress this output, but that's not convenient because the machine I'm recording the videos on isn't really setup for dev.

---

CIDER is amazing, I use it all day every day, and it's absolutely critical for me to solve my users' worthy problems. 

Thank you in advance for your time and consideration!

**Comment by vemv** [comment]
Hi!

In case the feedback helps, the noisy output is simply the REPL's normal output for `board->image`. It is the normal expectation for any given repl that evaluating something gets a value printed (it's the P in REPL).

The fact that an image gets printed doesn't necessarily invalidate that. It also plausibly hinders debugging/traceability (here we see it's a `BufferedImage`; what if it was another class? That can be valuable info).

It can also complicate CIDER's impl since, as hinted, we'd have to change the basic functioning of what a RE**P**L does.

So personally I'd vote for leaving things simple.

Cheers - V

**Comment by bbatsov** [comment]
That'd be fine by me. I'm all for keeping things simple (and doing less work :D).

**Comment by vemv** [comment]
One can always define a custom https://clojuredocs.org/clojure.core/print-method in his project, making `BufferedImage` less noisy (you might even get away with making it print _nothing at all_)

Hope that helps @harold !

**Comment by harold** [comment]
Indeed, overriding `print-method` is what I ended up doing. Thanks, both.

@bbatsov - always great to see your name around these parts. Hope you've been well.
