### ISSUE TITLE
CircleCI windows credits

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/cider#3046]
Currently all our windows builds on CircleCI are failing. Seems the situation is as follows

- as an open source project we get 400,000 builds/month, but that's only for Linux builds
- for the windows build we fall back to their regular "free" plan, which includes 2500 credits, and we've well exhausted that.

CircleCI is a Clojure shop and I'm sure that a significant number of their devs use CIDER, so it's really in their best interest to give us some support. I reached out to a friend at CircleCI. He basically said "we're not sure yet how we're going to deal with cases like this, but in the meanwhile we might be able to do something. How many credits would you need?"

So... can we come up with estimate for that?

Alternatively we could port the windows builds to GH actions.

**Comment by vemv** [comment]
Perhaps paying wouldn't be out of the question - concurrency rocks and can encourage us to write more extensive build matrices

For example for Suitable I had planned a few extra dimensions: https://github.com/clojure-emacs/clj-suitable/blob/ced9e834666510154de794821ecd9f2e680af2c8/.circleci/config.yml#L132-L136

IIRC @bbatsov already had some predisposition to get us this upgrade

**Comment by bbatsov** [comment]
I'm fine with paying for this, if we need it, but I was also pondering if won't be better to use GHA instead - I've been using it for the Windows builds of RuboCop for a while now and I've been quite pleased with it. In general I'm not sure if there are any advantages to using CircleCI over GHA. 

>  "we're not sure yet how we're going to deal with cases like this, but in the meanwhile we might be able to do something. How many credits would you need?"

I guess 100k credits will be plenty, probably we won't need even half of those. I'm too lazy to do real estimates, and I guess for them it should be more or less the same. :-)

**Comment by plexus** [comment]
I'll pass that on and see what happens.

> I'm not sure if there are any advantages to using CircleCI over GHA

Whatever works. The only counterargument I see is that someone needs to port the config, I don't find tweaking CI particularly satisfying work. But perhaps only porting the windows builds isn't too bad.

**Comment by vemv** [comment]
I'm somewhat biased against GHA (even thought I chose it myself for https://github.com/clojure-emacs/enrich-classpath/) - it's flaky and it's not rare to see people recommending it only for 'actions', not for CI. Basically because it's flakier than the competition. Jobs can be occasionally delayed for minutes/hours.

It doesn't help that they arranged the ways such that they have a constant incoming flow of freeloaders :) i.e. we share the same resource pool with a lot of noisy neighbors.

To be fair GHA has nice support for macOS as well whereas in Circle it's much more appdev-oriented.

---

(btw maybe I'm conflating `cider` with `clojure-emacs` CI here... I'm not affected at all by `cider` choices, but would definitely appreciate the paid concurrency grid for `refactor-nrepl`, `orchard`, `cider-nrepl` and `suitable`)

**Comment by plexus** [comment]
My CircleCI contact just let me know they have bumped up the limit of windows builds, and we should be fine for the foreseeable future. Rejoice!

**Comment by bbatsov** [comment]
Thanks! 🙇‍♂️
