### ISSUE TITLE
Failing integration test

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3121]
@ikappaki Can you take a look at this failure (I think you're the author of this test):

```
========================================
nrepl-client-lifecycle start and stop nrepl client process

Traceback (most recent call last):
  error((void-variable params))
  apply(format-message (void-variable params))
  format-message((void-variable params))
error: (wrong-type-argument stringp (void-variable params))
```

I see the test refers to an unset `params` variable and I guess the byte-compilation fixes broke it somehow, although I'm not sure how it passed in the first place.

**Comment by Bost** [comment]
Also it seems like the .dir-locals.el is not read, since the latest update. (I have CIDER 1.2.0 (Nice), nREPL 0.9.0, Clojure 1.10.3, Java 16.0.2, I do update packages every day and yesterday everything was fine)

**Comment by bbatsov** [comment]
@Bost Do you mean that something broke after https://github.com/clojure-emacs/cider/commit/b07208f2979483b95606e1fd10f650a8104004ee ? As most changes are cosmetic I can't immediately figure out a connection with `.dir-locals.el`, but I'll take a closer look.

> Edit: not everything was fine yesterday, ehm :) but I could work.

Are you referring to the issue with `cider-version`?

**Comment by ikappaki** [comment]
> @ikappaki Can you take a look at this failure (I think you're the author of this test):
> 
> ```
> ========================================
> nrepl-client-lifecycle start and stop nrepl client process
> 
> Traceback (most recent call last):
>   error((void-variable params))
>   apply(format-message (void-variable params))
>   format-message((void-variable params))
> error: (wrong-type-argument stringp (void-variable params))
> ```
> 
> I see the test refers to an unset `params` variable and I guess the byte-compilation fixes broke it somehow, although I'm not sure how it passed in the first place.

Hi @bbatsov, the recent file socket support referenced a `params` variable that was never supposed to be in scope for this test, it was defined as `:var` in another. This should never have worked to begin with and should have failed from the start. Enabling lexical scope corrected this and thus the test failed as it was supposed to. `buttercup` does suggests using lexical scope with `:var` in their documentation. Fixed with #3122.

Thanks

**Comment by Bost** [comment]
> @Bost Do you mean that something broke after [b07208f](https://github.com/clojure-emacs/cider/commit/b07208f2979483b95606e1fd10f650a8104004ee) ? As most changes are cosmetic I can't immediately figure out a connection with `.dir-locals.el`, but I'll take a closer look.

The first commit which doesn't properly read the .dir-locals.el is the c60598f (Remove cider-compat.el - It's not longer needed now that we don't support Emacs 25.)' and that's odd since I have:
```
$ emacs --version
GNU Emacs 27.2.50
...
```

> > Edit: not everything was fine yesterday, ehm :) but I could work.
> 
> Are you referring to the issue with `cider-version`?

I don't know what issue do you mean. The cosmetic problem I had yesterday was that no banner and no REPL prompt got displayed after invoking M-x cider-jack-in-clj. Except that everything was working fine.

**Comment by bbatsov** [comment]
@Bost Can you file a separate ticket, so I won't forget to look into this?

In general `.dir-locals.el` shouldn't be affected by anything in CIDER, as it's a core mechanism of Emacs itself.
