### ISSUE TITLE
A similar function to cider-eval-last-sexp-to-repl

### ISSUE THREAD

**Issue by prairie-guy** [clojure-emacs/cider#3150]
**Is your feature request related to a problem? Please describe.**
I would like to have a function similar to **cider-eval-last-sexp-to-repl**. The changes would be: 

1. Have the evaluated results always sent to the end of the REPL, not at wherever the point is within the REPL. 
2. Send the equivalent of a “return” to the REPL so that the REPL cursor point is “refreshed”.

I’ve recently started testing/running code from within a (comment . . .) block. Historically, I’ve reloaded the clojure file and/or typed code directly in the REPL. I really enjoy the new style. (It seems very popular with the Calva extension in VSCode, but I am way too invested in Emacs.) Ideally, I would be within a clojure buffer, execute an sexp, see the result in the REPL and iterate, all from within the clojure buffer without having to jump to/from the REPL.

It’s entirely possible that this functionality already exists, in which case I would be delighted. (I have looked closely, so I apologize if I’ve missed it.)

**Comment by vemv** [comment]
There is is `cider-eval-sexp-at-point` in case it helps:

<img src="https://user-images.githubusercontent.com/10757633/80720513-0ea94a00-8b0e-11ea-9509-a9c1d1281c13.png"/>

It doesn't sent the sexpr to the repl as described, but if you are used to this workflow, you might as well wonder why you want a repl anymore :) i.e. it seems just a roundabout step.

Otherwise, for accomplishing what you indicate you can add `advice-add`:

* `1.` would be a `:before` advice
* `2.` would be an `:after` advice

Let us know how these work for you.

Cheers - V
