### ISSUE TITLE
CI: Failing lint step

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3178]
The `test-lint` job keeps failing, I wonder what could we do about it?

https://app.circleci.com/pipelines/github/clojure-emacs/cider/1179/workflows/2744caf7-cdf6-4ed2-aca8-8eafe0f7324c/jobs/5440

The error in question (`Error: value returned from (fboundp 'package-get-version) is unused`) seems a false positive, where would we report that? Is there something we could upgrade first?

Worst-case scenario, we could remove the `--warnings-as-errors` flag and do our own grepping with some minimal blaklisting logic.

**Comment by ikappaki** [comment]
Hi @vemv,

this is a bit tricky ... The warning is legit, but the actual text is misleading. What is happening here is that at compile time the compiler encountered a conditional whose both branches return `nil`.

``` elisp
(if (fboundp 'package-get-version)
      (package-get-version)
    nil))
``` 
Or to simplify what the compiler sees:

``` elisp
(if (<runtime-predicate>)
     nil
   nil)
```
and thus it complains that the return value of the `(runtime-predicate)` is unused since the if block will return `nil`, no need to look at it.

I suppose you might have tried to run the compilation locally, and most likely it succeed without a warning/error
``` batch
d:/src/cider $ rm cider-util.elc; eldev.bat -dtT compile --warnings-as-errors cider-util.el
...
[00:01.099]  Byte-compiling file `cider-util.el'...
[00:01.099]  Loading file `cider-util.el' before byte-compiling it...
[00:01.273]  Loading the byte-compiled file `cider-util.elc'...
[00:01.278]  Saving target dependencies to file `.eldev/28.1/target-dependencies.build'...
```

This is because `(package-get-version)` does return a non-nil value on your local checkout, i.e. the `(<runtime-predicate>)` has to be checked at runtime to check which branch to take, so it is going to be used:

``` elisp
(if (<runtime-predicate>)
     "<package-version>"
   nil)
```

Why does it fail on the Circle CI? because `package-get-version` returns nil when it runs over there! Why does it only return `nil` on Circle? Because `package-get-version` on Emacs 27.x will only consider getting package-versions if the parent directory is name the same as the package name, i.e. `cider` in our case  (This has been improved on 28.x and should not be a problem any more). On circle ci the parnet directory is named "project" (there is nothing wrong with that):

``` bash
#!/bin/bash -eo pipefail
eldev -dtT compile --warnings-as-errors

[00:00.007]  Started up on Thu Mar 31 09:59:55 2022
[00:00.007]  Running on GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
[00:00.007]  Project directory: `/root/project/'

```

`package-get-version` is a bad boy, is `declare`d as `pure` but it is nothing like this since it depends on external variables. Because it is pure, it's return value is picked up by the compiler as constant and thus we get in this situation.

How do we fix this? The same warning will be issued with `when` or `and` (e.g. consider `(when (<runtime-predicate) nil)`  or` (and (<runtime-predicate>) nil)`, both always return `nil` irrespective of the predicate value at runtime. The only thing that works is `cond`, since the compiler apparently does not try to aggressively optimise it.

PR to follow.
