### ISSUE TITLE
Ask if you want to launch a browser window when starting a CLJS browser REPL

### ISSUE THREAD

**Issue by lilactown** [clojure-emacs/cider#3216]
**Is your feature request related to a problem? Please describe.**

I have a project that I'm developing using the default CLJS browser REPL.
Currently, when the CLJS browser REPL connects it launches my default browser with the page that hosts the REPL environment.
I would like to be able to use Chrome and Firefox for testing purposes, however I use Safari as my main browser.

**Describe the solution you'd like**

I would like to be able to choose whether to launch a window using my default browser, or open the host + port in a browser of my choosing myself, similar to the way that other CLJS REPL launches prompt with a y/n question of whether to open a browser window.

**Describe alternatives you've considered**

I considered looking into providing a choice of which browser to launch, but this seemed a lot harder and isn't something that CIDER already provides.

**Additional context**

After some research, I found that the `browser` REPL type runs this code on launch:

```
"(do (require 'cljs.repl.browser) (cider.piggieback/cljs-repl (cljs.repl.browser/repl-env)))"
```

It is `cljs.repl.browser/repl-env` which controls whether the browser is opened or not.

I was able to add a custom REPL type to my spacemacs config that allows me to work around this for now:

```
(with-eval-after-load 'cider
    (cider-register-cljs-repl-type
     'browser-no-open
     "(do (require 'cljs.repl.browser) (cider.piggieback/cljs-repl (cljs.repl.browser/repl-env :launch-browser false)))"))
```

I think that the `browser` REPL type could prompt before running this command and then pass in the `:launch-browser` option if necessary. Alternatively, we could always pass in `:launch-browser false` and open the window the same way we do for `shadow` et al.

**Comment by vemv** [comment]
You probably can rebind `cider-cljs-repl-types` prior to `cider-jack-in-cljs`, such that `browser` has a custom value.

Normally I'd suggest opening a PR for introducing a defcustom, but because `defvar cider-cljs-repl-types` is a public var (and not a function), it's less amenable to defcustoms.

We wouldn't want to inflict a breaking change (var -> function) or refactoring for what today appears to be a minor use case.

Because there are two workarounds (`cider-register-cljs-repl-type`, binding `cider-cljs-repl-types`) I'll close the issue, but feel free to continue the conversation.

Cheers - V
