### ISSUE TITLE
"Unexpected CIDER middleware error"

### ISSUE THREAD

**Issue by bhlieberman** [clojure-emacs/cider#3222]
When starting a CIDER repl inside a clj/cljs project I receive a `java.lang.Exception`: `Either 'symbol', or ('class', 'member') must be supplied`. I used the lein-reagent template available at https://github.com/reagent-project/reagent-template and created the project with the `test` and `cider` profiles. When I ran `M-x cider-jack-in` in one of my `.clj` files I got the exception. But the connection otherwise succeeded, as far as I can tell.

**Comment by vemv** [comment]
Could you please post the entire stacktrace?

Thanks - V

**Comment by bhlieberman** [comment]
![cider-error-snap](https://user-images.githubusercontent.com/60364696/178792414-46fc09ca-4480-4945-a59d-d66ea1762b4e.png)

**Comment by vemv** [comment]
That's not the entire stacktrace

Anyway, check out the first `WARNING` about a version mismatch. We cannot offer support while there's one.

For a stable experience I'd recommend that you use cider from `melpa-stable` instead of `melpa`. So typically you should be using CIDER 1.4.1, and a cider-nrepl that matches said cider.el.

Feel free to reopen the issue when the two items are satisfied

Cheers - V
