### ISSUE TITLE
cider-pprint-eval-last-sexp should keep last pprint result if this sexp resulted in error

### ISSUE THREAD

**Issue by Inc0n** [clojure-emacs/cider#3269]
**Is your feature request related to a problem? Please describe.**

In my current project, a puzzle game. Having current state returned from functions and `pprint`ed using  `C-c C-p` `cider-pprint-eval-last-sexp` is a cool way to help visualize current game state.
But sometimes sexp evaluating may throws error, which clears `*cider-result*`.
Making it slightly troublesome for me, i.e. getting that "visualization" back up.

**Describe the solution you'd like**

So, keep`*cider-results*` the way it is if an error is thrown. And perhaps this can be made as an optional customizable feature using a variable as well.

**Describe alternatives you've considered**

1. Go back to the right function and do `C-c C-p` on them to get the `pprint`ed game state back.
2. *cider-results* have a fixed sexp (i.e. the global game state variable)  to eval and `pprint` after every `cider-pprint-eval-last-sexp`

**Additional context**

**Comment by vemv** [comment]
I worked on this area today (https://github.com/clojure-emacs/cider/pull/3558) and I'm not sure that keeping `*cider-results*` unaltered is desirable.

For one thing it's not even _easy_ - not without rethinking completely its implementation.

One alternative approach is to `cider-inspect` the atom representing your puzzle state and then use [`cider-inspector-refresh`](https://docs.cider.mx/cider/debugging/inspector.html#usage) to refresh this atom whenever you need so.

Hope this is a satisactory answer - feel free to continue the conversation otherwise.

Cheers - V
