### ISSUE TITLE
ClojureScript dynamic font lock not working for new functions (`var`)

### ISSUE THREAD

**Issue by nikolavojicic** [clojure-emacs/cider#3393]
First go through this issue https://github.com/clojure-emacs/cider/issues/3385 and use cider-nrepl version 0.34.0.

## Expected behavior

User defined functions should be dynamically highlighted.

## Actual behavior

In ClojureScript, new user defined functions are not dynamically highlighted but old ones are (there is no such problem in Clojure).

<img width="212" alt="258242216-97a9316e-a64a-4efd-881e-99b61a3842c4" src="https://github.com/clojure-emacs/cider/assets/10941031/0d5095e4-77e5-4e62-b801-adc2056b4e63">

## Steps to reproduce the problem

1. `(setq cider-font-lock-dynamically '(macro core function var))` in your init
2. Run cider-jack-in-cljs
3. Choose shadow
4. Choose :app
5. Visit application in browser
6. Write the code from above
7. Evaluate that code

There is no such problem if you write `(setq cider-font-lock-dynamically '(macro core function deprecated))` in your config, i.e. the problem is probably with `var`.

**Comment by vemv** [comment]
Thanks for the new issue, much easier to manage things that way 👍

**Comment by vemv** [comment]
I can repro (note to self: the key to reproing is creating a new function).

A few observations:

* from the nrepl log, I can see that the changed-namespaces key sometimes doesn't come for cljs
  * e.g. for a jvm repl, it always comes after a simple repl interaction (eval op), for cljs, never
  * a way to cause changed-namespaces to be included: change between .cljs namespaces, causing a `in-ns ,,,` eval

It's as if `cider.nrepl.middleware.track-state` sometimes failed to send anything at all, for cljs. Worth noting that it sends stuff async, with an `agent`. Maybe errors are being swallowed, although error handling seems ok.

---

Fixing this should be pretty important beyond the syntax highlighting, because the `track-state` middleware supports all type of functionality.

**Comment by vemv** [comment]
I have the impression that the track-state middleware runs just once for cljs, then never again.

Maybe it has to do with middleware order?

This is shadow's order:

https://github.com/thheller/shadow-cljs/blob/bb586a0fab475c13c6d090164c4122f2782308e3/src/main/shadow/cljs/devtools/server/nrepl.clj#L98-L105

...emphasis on `nrepl.middleware.interruptible-eval/interruptible-eval` being placed after `cider.nrepl/cider-middleware` - it might be usually the opposite?

**Comment by bbatsov** [comment]
> e.g. for a jvm repl, it always comes after a simple repl interaction (eval op), for cljs, never

It's possible, like many things in CIDER it was designed for Clojure in the days where ClojureScript wasn't really a thing. I'm also wondering if it behaves in the same way with different ClojureScript REPLs given all the differences between them.

**Comment by vemv** [comment]
Fixed. You'd need to use cider-nrepl 0.35.0 and cider master.

Fixing this resulted in an overall improvement, beyond font-locking. So thanks for the heads up - don't hesitate to report more issues!
