### ISSUE TITLE
Completion of namespace-qualified vars fails for (partial-completion initials)

### ISSUE THREAD

**Issue by danlei** [clojure-emacs/cider#467]
When `partial-completion-mode` was deprecated in Emacs 24, I followed a recommendation from NEWS to get comparable behavior:

    (setq completion-styles '(partial-completion initials)
          completion-pcm-complete-word-inserts-delimiters t)

It does the job, and I have not had any problems with it so far, but it breaks completion of namespace-qualified vars in my fresh cider installation. There is no error message, only `No match`. Everything works fine without the above setup.

I am using CIDER 0.6.0snapshot (following master), Clojure 1.6.0-alpha3 (but it did not work with 1.5.1 either), nREPL 0.2.3 on Emacs 24.3.50, Ubuntu 12.04.4 LTS.

By the way, thanks for the great work!

**Comment by cichli** [comment]
I've noticed something similar, and I think it might be irrespective of `completion-styles`.

If I type `clojure.pprint/` and then start completion I get no completions; if I type `clojure.pp` and then select `clojure.pprint/` from the completion dropdown before starting completions, I get all the `clojure.pprint/` completions as expected.

This is most likely because the backend does not return anything namespace-qualified unless the prefix exactly matches `clojure.pprint/` (to limit the number of candidates returned when completing non-namespace-qualified prefixes), and we are not making a new backend call when we should be. One solution would be to ensure we make a new call if:

* the user types `/` and
* `cider-namespace-qualified-p` returns true for the new prefix
