### ISSUE TITLE
Buffers do not appear

### ISSUE THREAD

**Issue by dball** [clojure-emacs/cider#646]
After installing a new emacs config with the latest cider package from melpa, when I run either cider-jack-in or cider-connect to a running repl, I don't get a _cider_ or _nrepl_ buffer. I do get the _nrepl-connection_ and _nrepl-server_ buffers, but no nrepl buffer.

If I call nrepl-switch-to-repl-buffer, I get a message, "Wrong type argument: stringp, nil".

I'm using GNU Emacs 24.3.1 on OS X 10.9.3, with cider-20140619.914 and cider-nrepl-0.7.0-SNAPSHOT

**Comment by deas** [comment]
Just  had  exactly the same behavior. Reinstalling cider fixed it for me.

**Comment by scottdw** [comment]
[Link to mailing list discussion](https://groups.google.com/forum/#!topic/cider-emacs/upqmikE6sXQ). It appears to have something do with the compilation of the newer version when upgrading. Deleting and re-installing the package seems to fix it. Unfortunately this also destroys any evidence of the root cause of the problem.

If someone can reliably reproduce this issue again it would be informative if they backed up their current cider .elc files prior to reinstalling and did a comparison afterwards.
