### ISSUE TITLE
Implement a debugger

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#694]
A debugger is the biggest missing feature at this point and the biggest roadblock we have to conquer on the the road to CIDER 1.0. 

I'm not sure how to best approach this task. I see two principle options:

* Port the Ritz debugger to CIDER. That should be fairly straightforward (at least in theory). The debugger code is [here](https://github.com/pallet/ritz/tree/develop/debugger)(Clojure) and [here](https://github.com/pallet/ritz/blob/develop/nrepl/elisp/nrepl-ritz.el)(Emacs Lisp).

* Implement a new solution from scratch. I have no idea if we can approach this problem from a different angle than @hugoduncan did for ritz. Feel free to suggest ideas.

I guess option one is the way to go, but we should still discuss alternatives before we start working on this. I'll probably take a break from working on features after 0.7, since I'd rewrite most of the nREPL client code (which is not particularly middleware-friendly right now), so I'm inviting the other CIDER hackers and users to step up and help out with this feature.

**Comment by cddr** [comment]
Is anyone working on this? If not, I might have a bash.

**Comment by expez** [comment]
@cddr go for it, nothing has happened on this front

**Comment by bbatsov** [comment]
@cddr Go ahead. At clojure/conj @jeremyheiler expressed interest in working on this, but I haven't heard from him since.

I started a new (pretty time consuming) job last month and I won't be able to work on bigger CIDER features for at least a few months.

**Comment by jeremyheiler** [comment]
I started to go the JDI route. My goal has been to reimplement jdb in a REPL, because being able to debug Java from Clojure seems important. The way I've envision it is that there's a debugger backend which can be used by many debugger frontends.

Although, I do agree that a "jdb-like" interface might not be enough, or ideal, so I've paused working on it so I can give it some hammock time.

**Comment by razum2um** [comment]
Have you all seen https://github.com/razum2um/clj-debugger ? It's just a nifty wrapper around clojure.main/repl but it allows skipping, access to the fn's locals and some more. The best thing of it - it's all clojure.

But generally the most missing features to me: multithreaded breakpoint and tracing are likely to achieve only through some specials of jvm, like @jeremyheiler said.

**Comment by cddr** [comment]
Huh! Thanks @razum2um. It actually it looks like clj-debugger does the thing that was my highest priority so that's cool. However I think JDI is required for the other thing I miss from common lisp which is interactive examination of locals all the way up the stack at a breakpoint. In my efforts, I got stuck at making tools.jar available to cider-nrepl at plugin time.

**Comment by Bruce-Connor** [comment]
For reference. I'm trying my hand at something like this on #1019. 
So far it instruments code using `clj-debugger` and walks you through it.

**Comment by noisesmith** [comment]
> I got stuck at making tools.jar available to cider-nrepl at plugin time

yeah, the tools.jar situation is weird, unlike most things that come with your JVM it needs to be explicitly added to your classpath and will only be available from the JDK (not the JRE)

True debugging (with access to locals at every frame etc.) will definitely require the JDI interface, and having a separate debugging JVM that halts and then steps the debugged process. The "debug repl" approach seems the most sensible, because the sorts of interaction possible in the debugger are separate from what you do in a regular repl.

**Comment by bbatsov** [comment]
Closing this as #1019 was just merged.

**Comment by SlightlyCyborg** [comment]
@razum2um do you know if we ever solved the multithreading problem. See my comments at the bottom of #1775  to see the problem I am experiencing. My guess is that threading was never implemented.
