### ISSUE TITLE
Evaluating facts in midje-mode breaks with cider 8.1

### ISSUE THREAD

**Issue by cch1** [clojure-emacs/cider#884]
Using the latest released version of cider and the corresponding cider-nrepl (8.1), midje mode can no longer evaluate individual facts. Instead, the cider-error buffer is shown with no message and the fact is not evaluated.

Versions:
emacs 24.4.1
cider 20141120.1746 (8.1 reported when connected)
cider-nrepl 8.1
midje-mode 20131019.1357

Same issue raised with midje-mode, but I suspect the problem is with cider.  See https://github.com/dnaumov/midje-mode/issues/31

**Comment by benfleis** [comment]
For follow up (since I'm chasing this myself, with the intent of submitting a patch), the problem appears to lie here:

  https://github.com/dnaumov/midje-mode/blob/master/midje-mode.el#L204

combined with:

  https://github.com/clojure-emacs/cider/commit/3d21d014fac9080dfc38ff8c368ff2c99b9e6248

Afaict, cider obviated the use of nrepl-buffer-ns; midje-mode hasn't follow up with a change.

@bbatsov What is the right thing to do, in place of using nrepl-buffer-ns?
